package falcon.entity;

import java.math.BigDecimal;

import model.PlSqlEntity;

import oracle.jbo.Key;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 20 14:48:29 EET 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DostavkaTabPartOrdersImpl extends PlSqlEntity {
    @Override
    protected void callInsertProcedure(TransactionEvent transactionEvent) {
        callStoredProcedure("DELIVER_PKG.insert_deliver_tab_part(?,?,?)",
                            new Object[] { getOrderId(), getDostavkaId(), getDopSumma() });
    }

    @Override
    protected void callUpdateProcedure(TransactionEvent transactionEvent) {
        callStoredProcedure("DELIVER_PKG.update_order_from_deliver(?,?,?,?)",
                            new Object[] { getId(), getOrderId(), getSumma(), getDopSumma() });
    }

    @Override
    protected void callDeleteProcedure(TransactionEvent transactionEvent) {
        callStoredProcedure("DELIVER_PKG.delete_order_from_deliver(?)", new Object[] { getId() });
    }

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        Id {
            public Object get(DostavkaTabPartOrdersImpl obj) {
                return obj.getId();
            }

            public void put(DostavkaTabPartOrdersImpl obj, Object value) {
                obj.setId((Long)value);
            }
        }
        ,
        DostavkaId {
            public Object get(DostavkaTabPartOrdersImpl obj) {
                return obj.getDostavkaId();
            }

            public void put(DostavkaTabPartOrdersImpl obj, Object value) {
                obj.setDostavkaId((Long)value);
            }
        }
        ,
        OrderId {
            public Object get(DostavkaTabPartOrdersImpl obj) {
                return obj.getOrderId();
            }

            public void put(DostavkaTabPartOrdersImpl obj, Object value) {
                obj.setOrderId((BigDecimal)value);
            }
        }
        ,
        Summa {
            public Object get(DostavkaTabPartOrdersImpl obj) {
                return obj.getSumma();
            }

            public void put(DostavkaTabPartOrdersImpl obj, Object value) {
                obj.setSumma((BigDecimal)value);
            }
        }
        ,
        DopSumma {
            public Object get(DostavkaTabPartOrdersImpl obj) {
                return obj.getDopSumma();
            }

            public void put(DostavkaTabPartOrdersImpl obj, Object value) {
                obj.setDopSumma((BigDecimal)value);
            }
        }
        ,
        Dostavka {
            public Object get(DostavkaTabPartOrdersImpl obj) {
                return obj.getDostavka();
            }

            public void put(DostavkaTabPartOrdersImpl obj, Object value) {
                obj.setDostavka((DostavkaImpl)value);
            }
        }
        ,
        Orders {
            public Object get(DostavkaTabPartOrdersImpl obj) {
                return obj.getOrders();
            }

            public void put(DostavkaTabPartOrdersImpl obj, Object value) {
                obj.setOrders((EntityImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(DostavkaTabPartOrdersImpl object);

        public abstract void put(DostavkaTabPartOrdersImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ID = AttributesEnum.Id.index();
    public static final int DOSTAVKAID = AttributesEnum.DostavkaId.index();
    public static final int ORDERID = AttributesEnum.OrderId.index();
    public static final int SUMMA = AttributesEnum.Summa.index();
    public static final int DOPSUMMA = AttributesEnum.DopSumma.index();
    public static final int DOSTAVKA = AttributesEnum.Dostavka.index();
    public static final int ORDERS = AttributesEnum.Orders.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DostavkaTabPartOrdersImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("falcon.entity.DostavkaTabPartOrders");
    }

    /**
     * Gets the attribute value for Id, using the alias name Id.
     * @return the value of Id
     */
    public Long getId() {
        return (Long)getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Id.
     * @param value value to set the Id
     */
    public void setId(Long value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for DostavkaId, using the alias name DostavkaId.
     * @return the value of DostavkaId
     */
    public Long getDostavkaId() {
        return (Long)getAttributeInternal(DOSTAVKAID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DostavkaId.
     * @param value value to set the DostavkaId
     */
    public void setDostavkaId(Long value) {
        setAttributeInternal(DOSTAVKAID, value);
    }

    /**
     * Gets the attribute value for OrderId, using the alias name OrderId.
     * @return the value of OrderId
     */
    public BigDecimal getOrderId() {
        return (BigDecimal)getAttributeInternal(ORDERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrderId.
     * @param value value to set the OrderId
     */
    public void setOrderId(BigDecimal value) {
        setAttributeInternal(ORDERID, value);
    }

    /**
     * Gets the attribute value for Summa, using the alias name Summa.
     * @return the value of Summa
     */
    public BigDecimal getSumma() {
        return (BigDecimal)getAttributeInternal(SUMMA);
    }

    /**
     * Sets <code>value</code> as the attribute value for Summa.
     * @param value value to set the Summa
     */
    public void setSumma(BigDecimal value) {
        setAttributeInternal(SUMMA, value);
    }

    /**
     * Gets the attribute value for DopSumma, using the alias name DopSumma.
     * @return the value of DopSumma
     */
    public BigDecimal getDopSumma() {
        return (BigDecimal)getAttributeInternal(DOPSUMMA);
    }

    /**
     * Sets <code>value</code> as the attribute value for DopSumma.
     * @param value value to set the DopSumma
     */
    public void setDopSumma(BigDecimal value) {
        setAttributeInternal(DOPSUMMA, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity DostavkaImpl.
     */
    public DostavkaImpl getDostavka() {
        return (DostavkaImpl)getAttributeInternal(DOSTAVKA);
    }

    /**
     * Sets <code>value</code> as the associated entity DostavkaImpl.
     */
    public void setDostavka(DostavkaImpl value) {
        setAttributeInternal(DOSTAVKA, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getOrders() {
        return (EntityImpl)getAttributeInternal(ORDERS);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setOrders(EntityImpl value) {
        setAttributeInternal(ORDERS, value);
    }

    /**
     * @param id key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Long id) {
        return new Key(new Object[]{id});
    }


}
