package falcon.entity;

import java.math.BigDecimal;

import model.PlSqlEntity;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 29 19:47:28 EET 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OplataIschodImpl extends PlSqlEntity {
    @Override
    protected void callInsertProcedure(TransactionEvent transactionEvent) {
    }

    @Override
    protected void callUpdateProcedure(TransactionEvent transactionEvent) {
        callStoredProcedure("oplata_ischod_pkg.update_oplataischod(?,?)",
                            new Object[] { getId(), getDat() });
    }

    @Override
    protected void callDeleteProcedure(TransactionEvent transactionEvent) {
        callStoredProcedure("oplata_ischod_pkg.delete_oplataischod(?)",
                            new Object[] { getId()});
    }

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        Id {
            public Object get(OplataIschodImpl obj) {
                return obj.getId();
            }

            public void put(OplataIschodImpl obj, Object value) {
                obj.setId((BigDecimal)value);
            }
        }
        ,
        SyncStr {
            public Object get(OplataIschodImpl obj) {
                return obj.getSyncStr();
            }

            public void put(OplataIschodImpl obj, Object value) {
                obj.setSyncStr((String)value);
            }
        }
        ,
        Deleted {
            public Object get(OplataIschodImpl obj) {
                return obj.getDeleted();
            }

            public void put(OplataIschodImpl obj, Object value) {
                obj.setDeleted((Integer)value);
            }
        }
        ,
        Dat {
            public Object get(OplataIschodImpl obj) {
                return obj.getDat();
            }

            public void put(OplataIschodImpl obj, Object value) {
                obj.setDat((Timestamp)value);
            }
        }
        ,
        SyncKey {
            public Object get(OplataIschodImpl obj) {
                return obj.getSyncKey();
            }

            public void put(OplataIschodImpl obj, Object value) {
                obj.setSyncKey((Integer)value);
            }
        }
        ,
        Posted {
            public Object get(OplataIschodImpl obj) {
                return obj.getPosted();
            }

            public void put(OplataIschodImpl obj, Object value) {
                obj.setPosted((Integer)value);
            }
        }
        ,
        Num {
            public Object get(OplataIschodImpl obj) {
                return obj.getNum();
            }

            public void put(OplataIschodImpl obj, Object value) {
                obj.setNum((String)value);
            }
        }
        ,
        KontragId {
            public Object get(OplataIschodImpl obj) {
                return obj.getKontragId();
            }

            public void put(OplataIschodImpl obj, Object value) {
                obj.setKontragId((BigDecimal)value);
            }
        }
        ,
        UserId {
            public Object get(OplataIschodImpl obj) {
                return obj.getUserId();
            }

            public void put(OplataIschodImpl obj, Object value) {
                obj.setUserId((BigDecimal)value);
            }
        }
        ,
        DivisionId {
            public Object get(OplataIschodImpl obj) {
                return obj.getDivisionId();
            }

            public void put(OplataIschodImpl obj, Object value) {
                obj.setDivisionId((BigDecimal)value);
            }
        }
        ,
        OrganisationRef {
            public Object get(OplataIschodImpl obj) {
                return obj.getOrganisationRef();
            }

            public void put(OplataIschodImpl obj, Object value) {
                obj.setOrganisationRef((String)value);
            }
        }
        ,
        DogovorRef {
            public Object get(OplataIschodImpl obj) {
                return obj.getDogovorRef();
            }

            public void put(OplataIschodImpl obj, Object value) {
                obj.setDogovorRef((String)value);
            }
        }
        ,
        Summa {
            public Object get(OplataIschodImpl obj) {
                return obj.getSumma();
            }

            public void put(OplataIschodImpl obj, Object value) {
                obj.setSumma((BigDecimal)value);
            }
        }
        ,
        CurrId {
            public Object get(OplataIschodImpl obj) {
                return obj.getCurrId();
            }

            public void put(OplataIschodImpl obj, Object value) {
                obj.setCurrId((BigDecimal)value);
            }
        }
        ,
        Comments {
            public Object get(OplataIschodImpl obj) {
                return obj.getComments();
            }

            public void put(OplataIschodImpl obj, Object value) {
                obj.setComments((String)value);
            }
        }
        ,
        Kurs {
            public Object get(OplataIschodImpl obj) {
                return obj.getKurs();
            }

            public void put(OplataIschodImpl obj, Object value) {
                obj.setKurs((BigDecimal)value);
            }
        }
        ,
        Krantost {
            public Object get(OplataIschodImpl obj) {
                return obj.getKrantost();
            }

            public void put(OplataIschodImpl obj, Object value) {
                obj.setKrantost((BigDecimal)value);
            }
        }
        ,
        Version {
            public Object get(OplataIschodImpl obj) {
                return obj.getVersion();
            }

            public void put(OplataIschodImpl obj, Object value) {
                obj.setVersion((Timestamp)value);
            }
        }
        ,
        KassaId {
            public Object get(OplataIschodImpl obj) {
                return obj.getKassaId();
            }

            public void put(OplataIschodImpl obj, Object value) {
                obj.setKassaId((BigDecimal)value);
            }
        }
        ,
        Users {
            public Object get(OplataIschodImpl obj) {
                return obj.getUsers();
            }

            public void put(OplataIschodImpl obj, Object value) {
                obj.setUsers((EntityImpl)value);
            }
        }
        ,
        Currency {
            public Object get(OplataIschodImpl obj) {
                return obj.getCurrency();
            }

            public void put(OplataIschodImpl obj, Object value) {
                obj.setCurrency((EntityImpl)value);
            }
        }
        ,
        Kontragents {
            public Object get(OplataIschodImpl obj) {
                return obj.getKontragents();
            }

            public void put(OplataIschodImpl obj, Object value) {
                obj.setKontragents((EntityImpl)value);
            }
        }
        ,
        Kassa {
            public Object get(OplataIschodImpl obj) {
                return obj.getKassa();
            }

            public void put(OplataIschodImpl obj, Object value) {
                obj.setKassa((EntityImpl)value);
            }
        }
        ,
        Divisions {
            public Object get(OplataIschodImpl obj) {
                return obj.getDivisions();
            }

            public void put(OplataIschodImpl obj, Object value) {
                obj.setDivisions((EntityImpl)value);
            }
        }
        ,
        OplataIschodTabPart {
            public Object get(OplataIschodImpl obj) {
                return obj.getOplataIschodTabPart();
            }

            public void put(OplataIschodImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(OplataIschodImpl object);

        public abstract void put(OplataIschodImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ID = AttributesEnum.Id.index();
    public static final int SYNCSTR = AttributesEnum.SyncStr.index();
    public static final int DELETED = AttributesEnum.Deleted.index();
    public static final int DAT = AttributesEnum.Dat.index();
    public static final int SYNCKEY = AttributesEnum.SyncKey.index();
    public static final int POSTED = AttributesEnum.Posted.index();
    public static final int NUM = AttributesEnum.Num.index();
    public static final int KONTRAGID = AttributesEnum.KontragId.index();
    public static final int USERID = AttributesEnum.UserId.index();
    public static final int DIVISIONID = AttributesEnum.DivisionId.index();
    public static final int ORGANISATIONREF = AttributesEnum.OrganisationRef.index();
    public static final int DOGOVORREF = AttributesEnum.DogovorRef.index();
    public static final int SUMMA = AttributesEnum.Summa.index();
    public static final int CURRID = AttributesEnum.CurrId.index();
    public static final int COMMENTS = AttributesEnum.Comments.index();
    public static final int KURS = AttributesEnum.Kurs.index();
    public static final int KRANTOST = AttributesEnum.Krantost.index();
    public static final int VERSION = AttributesEnum.Version.index();
    public static final int KASSAID = AttributesEnum.KassaId.index();
    public static final int USERS = AttributesEnum.Users.index();
    public static final int CURRENCY = AttributesEnum.Currency.index();
    public static final int KONTRAGENTS = AttributesEnum.Kontragents.index();
    public static final int KASSA = AttributesEnum.Kassa.index();
    public static final int DIVISIONS = AttributesEnum.Divisions.index();
    public static final int OPLATAISCHODTABPART = AttributesEnum.OplataIschodTabPart.index();

    /**
     * This is the default constructor (do not remove).
     */
    public OplataIschodImpl() {
    }

    /**
     * Gets the attribute value for Id, using the alias name Id.
     * @return the value of Id
     */
    public BigDecimal getId() {
        return (BigDecimal)getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Id.
     * @param value value to set the Id
     */
    public void setId(BigDecimal value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for SyncStr, using the alias name SyncStr.
     * @return the value of SyncStr
     */
    public String getSyncStr() {
        return (String)getAttributeInternal(SYNCSTR);
    }

    /**
     * Sets <code>value</code> as the attribute value for SyncStr.
     * @param value value to set the SyncStr
     */
    public void setSyncStr(String value) {
        setAttributeInternal(SYNCSTR, value);
    }

    /**
     * Gets the attribute value for Deleted, using the alias name Deleted.
     * @return the value of Deleted
     */
    public Integer getDeleted() {
        return (Integer)getAttributeInternal(DELETED);
    }

    /**
     * Sets <code>value</code> as the attribute value for Deleted.
     * @param value value to set the Deleted
     */
    public void setDeleted(Integer value) {
        setAttributeInternal(DELETED, value);
    }

    /**
     * Gets the attribute value for Dat, using the alias name Dat.
     * @return the value of Dat
     */
    public Timestamp getDat() {
        return (Timestamp)getAttributeInternal(DAT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Dat.
     * @param value value to set the Dat
     */
    public void setDat(Timestamp value) {
        setAttributeInternal(DAT, value);
    }

    /**
     * Gets the attribute value for SyncKey, using the alias name SyncKey.
     * @return the value of SyncKey
     */
    public Integer getSyncKey() {
        return (Integer)getAttributeInternal(SYNCKEY);
    }

    /**
     * Sets <code>value</code> as the attribute value for SyncKey.
     * @param value value to set the SyncKey
     */
    public void setSyncKey(Integer value) {
        setAttributeInternal(SYNCKEY, value);
    }

    /**
     * Gets the attribute value for Posted, using the alias name Posted.
     * @return the value of Posted
     */
    public Integer getPosted() {
        return (Integer)getAttributeInternal(POSTED);
    }

    /**
     * Sets <code>value</code> as the attribute value for Posted.
     * @param value value to set the Posted
     */
    public void setPosted(Integer value) {
        setAttributeInternal(POSTED, value);
    }

    /**
     * Gets the attribute value for Num, using the alias name Num.
     * @return the value of Num
     */
    public String getNum() {
        return (String)getAttributeInternal(NUM);
    }

    /**
     * Sets <code>value</code> as the attribute value for Num.
     * @param value value to set the Num
     */
    public void setNum(String value) {
        setAttributeInternal(NUM, value);
    }

    /**
     * Gets the attribute value for KontragId, using the alias name KontragId.
     * @return the value of KontragId
     */
    public BigDecimal getKontragId() {
        return (BigDecimal)getAttributeInternal(KONTRAGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for KontragId.
     * @param value value to set the KontragId
     */
    public void setKontragId(BigDecimal value) {
        setAttributeInternal(KONTRAGID, value);
    }

    /**
     * Gets the attribute value for UserId, using the alias name UserId.
     * @return the value of UserId
     */
    public BigDecimal getUserId() {
        return (BigDecimal)getAttributeInternal(USERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for UserId.
     * @param value value to set the UserId
     */
    public void setUserId(BigDecimal value) {
        setAttributeInternal(USERID, value);
    }

    /**
     * Gets the attribute value for DivisionId, using the alias name DivisionId.
     * @return the value of DivisionId
     */
    public BigDecimal getDivisionId() {
        return (BigDecimal)getAttributeInternal(DIVISIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DivisionId.
     * @param value value to set the DivisionId
     */
    public void setDivisionId(BigDecimal value) {
        setAttributeInternal(DIVISIONID, value);
    }

    /**
     * Gets the attribute value for OrganisationRef, using the alias name OrganisationRef.
     * @return the value of OrganisationRef
     */
    public String getOrganisationRef() {
        return (String)getAttributeInternal(ORGANISATIONREF);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrganisationRef.
     * @param value value to set the OrganisationRef
     */
    public void setOrganisationRef(String value) {
        setAttributeInternal(ORGANISATIONREF, value);
    }

    /**
     * Gets the attribute value for DogovorRef, using the alias name DogovorRef.
     * @return the value of DogovorRef
     */
    public String getDogovorRef() {
        return (String)getAttributeInternal(DOGOVORREF);
    }

    /**
     * Sets <code>value</code> as the attribute value for DogovorRef.
     * @param value value to set the DogovorRef
     */
    public void setDogovorRef(String value) {
        setAttributeInternal(DOGOVORREF, value);
    }

    /**
     * Gets the attribute value for Summa, using the alias name Summa.
     * @return the value of Summa
     */
    public BigDecimal getSumma() {
        return (BigDecimal)getAttributeInternal(SUMMA);
    }

    /**
     * Sets <code>value</code> as the attribute value for Summa.
     * @param value value to set the Summa
     */
    public void setSumma(BigDecimal value) {
        setAttributeInternal(SUMMA, value);
    }

    /**
     * Gets the attribute value for CurrId, using the alias name CurrId.
     * @return the value of CurrId
     */
    public BigDecimal getCurrId() {
        return (BigDecimal)getAttributeInternal(CURRID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CurrId.
     * @param value value to set the CurrId
     */
    public void setCurrId(BigDecimal value) {
        setAttributeInternal(CURRID, value);
    }

    /**
     * Gets the attribute value for Comments, using the alias name Comments.
     * @return the value of Comments
     */
    public String getComments() {
        return (String)getAttributeInternal(COMMENTS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Comments.
     * @param value value to set the Comments
     */
    public void setComments(String value) {
        setAttributeInternal(COMMENTS, value);
    }

    /**
     * Gets the attribute value for Kurs, using the alias name Kurs.
     * @return the value of Kurs
     */
    public BigDecimal getKurs() {
        return (BigDecimal)getAttributeInternal(KURS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Kurs.
     * @param value value to set the Kurs
     */
    public void setKurs(BigDecimal value) {
        setAttributeInternal(KURS, value);
    }

    /**
     * Gets the attribute value for Krantost, using the alias name Krantost.
     * @return the value of Krantost
     */
    public BigDecimal getKrantost() {
        return (BigDecimal)getAttributeInternal(KRANTOST);
    }

    /**
     * Sets <code>value</code> as the attribute value for Krantost.
     * @param value value to set the Krantost
     */
    public void setKrantost(BigDecimal value) {
        setAttributeInternal(KRANTOST, value);
    }

    /**
     * Gets the attribute value for Version, using the alias name Version.
     * @return the value of Version
     */
    public Timestamp getVersion() {
        return (Timestamp)getAttributeInternal(VERSION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Version.
     * @param value value to set the Version
     */
    public void setVersion(Timestamp value) {
        setAttributeInternal(VERSION, value);
    }

    /**
     * Gets the attribute value for KassaId, using the alias name KassaId.
     * @return the value of KassaId
     */
    public BigDecimal getKassaId() {
        return (BigDecimal)getAttributeInternal(KASSAID);
    }

    /**
     * Sets <code>value</code> as the attribute value for KassaId.
     * @param value value to set the KassaId
     */
    public void setKassaId(BigDecimal value) {
        setAttributeInternal(KASSAID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getUsers() {
        return (EntityImpl)getAttributeInternal(USERS);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setUsers(EntityImpl value) {
        setAttributeInternal(USERS, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getCurrency() {
        return (EntityImpl)getAttributeInternal(CURRENCY);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setCurrency(EntityImpl value) {
        setAttributeInternal(CURRENCY, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getKontragents() {
        return (EntityImpl)getAttributeInternal(KONTRAGENTS);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setKontragents(EntityImpl value) {
        setAttributeInternal(KONTRAGENTS, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getKassa() {
        return (EntityImpl)getAttributeInternal(KASSA);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setKassa(EntityImpl value) {
        setAttributeInternal(KASSA, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getDivisions() {
        return (EntityImpl)getAttributeInternal(DIVISIONS);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setDivisions(EntityImpl value) {
        setAttributeInternal(DIVISIONS, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getOplataIschodTabPart() {
        return (RowIterator)getAttributeInternal(OPLATAISCHODTABPART);
    }

    /**
     * @param id key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal id) {
        return new Key(new Object[]{id});
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("falcon.entity.OplataIschod");
    }
}
