package falcon.entity;

import java.math.BigDecimal;

import model.PlSqlEntity;

import oracle.jbo.Key;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 29 19:31:00 EET 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OplataIschodTabPartImpl extends PlSqlEntity {
    @Override
    protected void callInsertProcedure(TransactionEvent transactionEvent) {
    }

    @Override
    protected void callUpdateProcedure(TransactionEvent transactionEvent) {
        callStoredProcedure("oplata_ischod_pkg.update_oplataischod_tab_part(?,?)",
                            new Object[] { getId(), getSumma() });
    }

    @Override
    protected void callDeleteProcedure(TransactionEvent transactionEvent) {
    }

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        Id {
            public Object get(OplataIschodTabPartImpl obj) {
                return obj.getId();
            }

            public void put(OplataIschodTabPartImpl obj, Object value) {
                obj.setId((BigDecimal)value);
            }
        }
        ,
        OplId {
            public Object get(OplataIschodTabPartImpl obj) {
                return obj.getOplId();
            }

            public void put(OplataIschodTabPartImpl obj, Object value) {
                obj.setOplId((BigDecimal)value);
            }
        }
        ,
        OrderId {
            public Object get(OplataIschodTabPartImpl obj) {
                return obj.getOrderId();
            }

            public void put(OplataIschodTabPartImpl obj, Object value) {
                obj.setOrderId((BigDecimal)value);
            }
        }
        ,
        Kurs {
            public Object get(OplataIschodTabPartImpl obj) {
                return obj.getKurs();
            }

            public void put(OplataIschodTabPartImpl obj, Object value) {
                obj.setKurs((BigDecimal)value);
            }
        }
        ,
        Kratnost {
            public Object get(OplataIschodTabPartImpl obj) {
                return obj.getKratnost();
            }

            public void put(OplataIschodTabPartImpl obj, Object value) {
                obj.setKratnost((BigDecimal)value);
            }
        }
        ,
        DogovorRef {
            public Object get(OplataIschodTabPartImpl obj) {
                return obj.getDogovorRef();
            }

            public void put(OplataIschodTabPartImpl obj, Object value) {
                obj.setDogovorRef((String)value);
            }
        }
        ,
        Summa {
            public Object get(OplataIschodTabPartImpl obj) {
                return obj.getSumma();
            }

            public void put(OplataIschodTabPartImpl obj, Object value) {
                obj.setSumma((BigDecimal)value);
            }
        }
        ,
        Orders {
            public Object get(OplataIschodTabPartImpl obj) {
                return obj.getOrders();
            }

            public void put(OplataIschodTabPartImpl obj, Object value) {
                obj.setOrders((EntityImpl)value);
            }
        }
        ,
        OplataIschod {
            public Object get(OplataIschodTabPartImpl obj) {
                return obj.getOplataIschod();
            }

            public void put(OplataIschodTabPartImpl obj, Object value) {
                obj.setOplataIschod((EntityImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(OplataIschodTabPartImpl object);

        public abstract void put(OplataIschodTabPartImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ID = AttributesEnum.Id.index();
    public static final int OPLID = AttributesEnum.OplId.index();
    public static final int ORDERID = AttributesEnum.OrderId.index();
    public static final int KURS = AttributesEnum.Kurs.index();
    public static final int KRATNOST = AttributesEnum.Kratnost.index();
    public static final int DOGOVORREF = AttributesEnum.DogovorRef.index();
    public static final int SUMMA = AttributesEnum.Summa.index();
    public static final int ORDERS = AttributesEnum.Orders.index();
    public static final int OPLATAISCHOD = AttributesEnum.OplataIschod.index();

    /**
     * This is the default constructor (do not remove).
     */
    public OplataIschodTabPartImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("falcon.entity.OplataIschodTabPart");
    }

    /**
     * Gets the attribute value for Id, using the alias name Id.
     * @return the value of Id
     */
    public BigDecimal getId() {
        return (BigDecimal)getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Id.
     * @param value value to set the Id
     */
    public void setId(BigDecimal value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for OplId, using the alias name OplId.
     * @return the value of OplId
     */
    public BigDecimal getOplId() {
        return (BigDecimal)getAttributeInternal(OPLID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OplId.
     * @param value value to set the OplId
     */
    public void setOplId(BigDecimal value) {
        setAttributeInternal(OPLID, value);
    }

    /**
     * Gets the attribute value for OrderId, using the alias name OrderId.
     * @return the value of OrderId
     */
    public BigDecimal getOrderId() {
        return (BigDecimal)getAttributeInternal(ORDERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrderId.
     * @param value value to set the OrderId
     */
    public void setOrderId(BigDecimal value) {
        setAttributeInternal(ORDERID, value);
    }

    /**
     * Gets the attribute value for Kurs, using the alias name Kurs.
     * @return the value of Kurs
     */
    public BigDecimal getKurs() {
        return (BigDecimal)getAttributeInternal(KURS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Kurs.
     * @param value value to set the Kurs
     */
    public void setKurs(BigDecimal value) {
        setAttributeInternal(KURS, value);
    }

    /**
     * Gets the attribute value for Kratnost, using the alias name Kratnost.
     * @return the value of Kratnost
     */
    public BigDecimal getKratnost() {
        return (BigDecimal)getAttributeInternal(KRATNOST);
    }

    /**
     * Sets <code>value</code> as the attribute value for Kratnost.
     * @param value value to set the Kratnost
     */
    public void setKratnost(BigDecimal value) {
        setAttributeInternal(KRATNOST, value);
    }

    /**
     * Gets the attribute value for DogovorRef, using the alias name DogovorRef.
     * @return the value of DogovorRef
     */
    public String getDogovorRef() {
        return (String)getAttributeInternal(DOGOVORREF);
    }

    /**
     * Sets <code>value</code> as the attribute value for DogovorRef.
     * @param value value to set the DogovorRef
     */
    public void setDogovorRef(String value) {
        setAttributeInternal(DOGOVORREF, value);
    }

    /**
     * Gets the attribute value for Summa, using the alias name Summa.
     * @return the value of Summa
     */
    public BigDecimal getSumma() {
        return (BigDecimal)getAttributeInternal(SUMMA);
    }

    /**
     * Sets <code>value</code> as the attribute value for Summa.
     * @param value value to set the Summa
     */
    public void setSumma(BigDecimal value) {
        setAttributeInternal(SUMMA, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getOrders() {
        return (EntityImpl)getAttributeInternal(ORDERS);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setOrders(EntityImpl value) {
        setAttributeInternal(ORDERS, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getOplataIschod() {
        return (EntityImpl)getAttributeInternal(OPLATAISCHOD);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setOplataIschod(EntityImpl value) {
        setAttributeInternal(OPLATAISCHOD, value);
    }

    /**
     * @param id key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal id) {
        return new Key(new Object[]{id});
    }


}
