package falcon.app_module;

import falcon.view.AccCurrencyViewImpl;
import falcon.view.AccFizDolgViewImpl;
import falcon.view.AccFizViewImpl;
import falcon.view.CatalogMetaTablesViewImpl;
import falcon.view.DivisionsViewImpl;
import falcon.view.DolgKontragentsImpl;
import falcon.view.DostavkaViewImpl;
import falcon.view.KonsultNameActiveViewImpl;
import falcon.view.KonsultNameViewImpl;
import falcon.view.MontagNameActiveImpl;
import falcon.view.MontagNameViewImpl;
import falcon.view.ObmenSettingsViewImpl;
import falcon.view.OplataIschodViewImpl;
import falcon.view.OtherZatratyViewImpl;
import falcon.view.ScalesZatratViewImpl;
import falcon.view.UserSettingsViewImpl;
import falcon.view.VwBepViewImpl;
import falcon.view.VwOrderViewImpl;
import falcon.view.VwSalesPerMonthViewImpl;
import falcon.view.VwSalesReportViewImpl;
import falcon.view.VwScalesViewImpl;
import falcon.view.VwUdevordersViewImpl;
import falcon.view.VwZatratyPerMonthViewImpl;
import falcon.view.ZamerNameViewActiveImpl;
import falcon.view.ZamerNameViewImpl;
import falcon.view.ZatratyPostViewImpl;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 16 18:48:04 EET 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for AccAccountingOstView1.
     * @return AccAccountingOstView1
     */
    public ViewObjectImpl getAccAccountingOstView1() {
        return (ViewObjectImpl)findViewObject("AccAccountingOstView1");
    }

    /**
     * Container's getter for AccAccountingView1.
     * @return AccAccountingView1
     */
    public ViewObjectImpl getAccAccountingView1() {
        return (ViewObjectImpl)findViewObject("AccAccountingView1");
    }

    /**
     * Container's getter for AccCostView1.
     * @return AccCostView1
     */
    public ViewObjectImpl getAccCostView1() {
        return (ViewObjectImpl)findViewObject("AccCostView1");
    }

    /**
     * Container's getter for AccFinancialResultView1.
     * @return AccFinancialResultView1
     */
    public ViewObjectImpl getAccFinancialResultView1() {
        return (ViewObjectImpl)findViewObject("AccFinancialResultView1");
    }

    /**
     * Container's getter for AccZatrView1.
     * @return AccZatrView1
     */
    public ViewObjectImpl getAccZatrView1() {
        return (ViewObjectImpl)findViewObject("AccZatrView1");
    }

    /**
     * Container's getter for BaseOfCalcScaleView1.
     * @return BaseOfCalcScaleView1
     */
    public ViewObjectImpl getBaseOfCalcScaleView1() {
        return (ViewObjectImpl)findViewObject("BaseOfCalcScaleView1");
    }

    /**
     * Container's getter for BaseOfClassificationView1.
     * @return BaseOfClassificationView1
     */
    public ViewObjectImpl getBaseOfClassificationView1() {
        return (ViewObjectImpl)findViewObject("BaseOfClassificationView1");
    }

    /**
     * Container's getter for CurrencyView1.
     * @return CurrencyView1
     */
    public ViewObjectImpl getCurrencyView1() {
        return (ViewObjectImpl)findViewObject("CurrencyView1");
    }

    /**
     * Container's getter for DivisionsSotrView1.
     * @return DivisionsSotrView1
     */
    public ViewObjectImpl getDivisionsSotrView1() {
        return (ViewObjectImpl)findViewObject("DivisionsSotrView1");
    }

    /**
     * Container's getter for DivisionsView1.
     * @return DivisionsView1
     */
    public DivisionsViewImpl getDivisionsView1() {
        return (DivisionsViewImpl)findViewObject("DivisionsView1");
    }

    /**
     * Container's getter for DostavkaTabPartOrdersView1.
     * @return DostavkaTabPartOrdersView1
     */
    public ViewObjectImpl getDostavkaTabPartOrdersView1() {
        return (ViewObjectImpl)findViewObject("DostavkaTabPartOrdersView1");
    }

    /**
     * Container's getter for DostavkaView1.
     * @return DostavkaView1
     */
    public DostavkaViewImpl getDostavkaView1() {
        return (DostavkaViewImpl)findViewObject("DostavkaView1");
    }

    /**
     * Container's getter for KassaView1.
     * @return KassaView1
     */
    public ViewObjectImpl getKassaView1() {
        return (ViewObjectImpl)findViewObject("KassaView1");
    }

    /**
     * Container's getter for KontragentsUserView1.
     * @return KontragentsUserView1
     */
    public ViewObjectImpl getKontragentsUserView1() {
        return (ViewObjectImpl)findViewObject("KontragentsUserView1");
    }

    /**
     * Container's getter for KontragentsView1.
     * @return KontragentsView1
     */
    public ViewObjectImpl getKontragentsView1() {
        return (ViewObjectImpl)findViewObject("KontragentsView1");
    }

    /**
     * Container's getter for MoveStatView1.
     * @return MoveStatView1
     */
    public ViewObjectImpl getMoveStatView1() {
        return (ViewObjectImpl)findViewObject("MoveStatView1");
    }

    /**
     * Container's getter for ObmenSettingsView1.
     * @return ObmenSettingsView1
     */
    public ObmenSettingsViewImpl getObmenSettingsView1() {
        return (ObmenSettingsViewImpl)findViewObject("ObmenSettingsView1");
    }

    /**
     * Container's getter for OrdersTabPartOplatyView1.
     * @return OrdersTabPartOplatyView1
     */
    public ViewObjectImpl getOrdersTabPartOplatyView1() {
        return (ViewObjectImpl)findViewObject("OrdersTabPartOplatyView1");
    }

    /**
     * Container's getter for OrdersTabPartZatratyView1.
     * @return OrdersTabPartZatratyView1
     */
    public ViewObjectImpl getOrdersTabPartZatratyView1() {
        return (ViewObjectImpl)findViewObject("OrdersTabPartZatratyView1");
    }

    /**
     * Container's getter for OrdersView1.
     * @return OrdersView1
     */
    public ViewObjectImpl getOrdersView1() {
        return (ViewObjectImpl)findViewObject("OrdersView1");
    }

    /**
     * Container's getter for OtherZatratyTabPartZatratyView1.
     * @return OtherZatratyTabPartZatratyView1
     */
    public ViewObjectImpl getOtherZatratyTabPartZatratyView1() {
        return (ViewObjectImpl)findViewObject("OtherZatratyTabPartZatratyView1");
    }

    /**
     * Container's getter for OtherZatratyView1.
     * @return OtherZatratyView1
     */
    public OtherZatratyViewImpl getOtherZatratyView1() {
        return (OtherZatratyViewImpl)findViewObject("OtherZatratyView1");
    }

    /**
     * Container's getter for RolesView1.
     * @return RolesView1
     */
    public ViewObjectImpl getRolesView1() {
        return (ViewObjectImpl)findViewObject("RolesView1");
    }

    /**
     * Container's getter for ScalesZatratView1.
     * @return ScalesZatratView1
     */
    public ScalesZatratViewImpl getScalesZatratView1() {
        return (ScalesZatratViewImpl)findViewObject("ScalesZatratView1");
    }

    /**
     * Container's getter for UserSettingsView1.
     * @return UserSettingsView1
     */
    public UserSettingsViewImpl getUserSettingsView1() {
        return (UserSettingsViewImpl)findViewObject("UserSettingsView1");
    }

    /**
     * Container's getter for UserTabPartContactsView1.
     * @return UserTabPartContactsView1
     */
    public ViewObjectImpl getUserTabPartContactsView1() {
        return (ViewObjectImpl)findViewObject("UserTabPartContactsView1");
    }

    /**
     * Container's getter for UsersView1.
     * @return UsersView1
     */
    public ViewObjectImpl getUsersView1() {
        return (ViewObjectImpl)findViewObject("UsersView1");
    }

    /**
     * Container's getter for ZatratyView1.
     * @return ZatratyView1
     */
    public ViewObjectImpl getZatratyView1() {
        return (ViewObjectImpl)findViewObject("ZatratyView1");
    }

    /**
     * Container's getter for AccAccountingOstView2.
     * @return AccAccountingOstView2
     */
    public ViewObjectImpl getAccAccountingOstView2() {
        return (ViewObjectImpl)findViewObject("AccAccountingOstView2");
    }

    /**
     * Container's getter for AccAccountingView2.
     * @return AccAccountingView2
     */
    public ViewObjectImpl getAccAccountingView2() {
        return (ViewObjectImpl)findViewObject("AccAccountingView2");
    }

    /**
     * Container's getter for AccZatrView2.
     * @return AccZatrView2
     */
    public ViewObjectImpl getAccZatrView2() {
        return (ViewObjectImpl)findViewObject("AccZatrView2");
    }

    /**
     * Container's getter for DivisionsView2.
     * @return DivisionsView2
     */
    public DivisionsViewImpl getDivisionsView2() {
        return (DivisionsViewImpl)findViewObject("DivisionsView2");
    }

    /**
     * Container's getter for AccCostView2.
     * @return AccCostView2
     */
    public ViewObjectImpl getAccCostView2() {
        return (ViewObjectImpl)findViewObject("AccCostView2");
    }

    /**
     * Container's getter for DivisionsSotrView2.
     * @return DivisionsSotrView2
     */
    public ViewObjectImpl getDivisionsSotrView2() {
        return (ViewObjectImpl)findViewObject("DivisionsSotrView2");
    }

    /**
     * Container's getter for DostavkaView2.
     * @return DostavkaView2
     */
    public DostavkaViewImpl getDostavkaView2() {
        return (DostavkaViewImpl)findViewObject("DostavkaView2");
    }

    /**
     * Container's getter for DostavkaView3.
     * @return DostavkaView3
     */
    public DostavkaViewImpl getDostavkaView3() {
        return (DostavkaViewImpl)findViewObject("DostavkaView3");
    }

    /**
     * Container's getter for DostavkaView4.
     * @return DostavkaView4
     */
    public DostavkaViewImpl getDostavkaView4() {
        return (DostavkaViewImpl)findViewObject("DostavkaView4");
    }

    /**
     * Container's getter for DostavkaTabPartOrdersView2.
     * @return DostavkaTabPartOrdersView2
     */
    public ViewObjectImpl getDostavkaTabPartOrdersView2() {
        return (ViewObjectImpl)findViewObject("DostavkaTabPartOrdersView2");
    }

    /**
     * Container's getter for KassaView2.
     * @return KassaView2
     */
    public ViewObjectImpl getKassaView2() {
        return (ViewObjectImpl)findViewObject("KassaView2");
    }

    /**
     * Container's getter for KassaView3.
     * @return KassaView3
     */
    public ViewObjectImpl getKassaView3() {
        return (ViewObjectImpl)findViewObject("KassaView3");
    }

    /**
     * Container's getter for AccAccountingOstView3.
     * @return AccAccountingOstView3
     */
    public ViewObjectImpl getAccAccountingOstView3() {
        return (ViewObjectImpl)findViewObject("AccAccountingOstView3");
    }

    /**
     * Container's getter for AccAccountingView3.
     * @return AccAccountingView3
     */
    public ViewObjectImpl getAccAccountingView3() {
        return (ViewObjectImpl)findViewObject("AccAccountingView3");
    }

    /**
     * Container's getter for AccFinancialResultView2.
     * @return AccFinancialResultView2
     */
    public ViewObjectImpl getAccFinancialResultView2() {
        return (ViewObjectImpl)findViewObject("AccFinancialResultView2");
    }

    /**
     * Container's getter for KontragentsView2.
     * @return KontragentsView2
     */
    public ViewObjectImpl getKontragentsView2() {
        return (ViewObjectImpl)findViewObject("KontragentsView2");
    }

    /**
     * Container's getter for AccCostView3.
     * @return AccCostView3
     */
    public ViewObjectImpl getAccCostView3() {
        return (ViewObjectImpl)findViewObject("AccCostView3");
    }

    /**
     * Container's getter for KontragentsUserView2.
     * @return KontragentsUserView2
     */
    public ViewObjectImpl getKontragentsUserView2() {
        return (ViewObjectImpl)findViewObject("KontragentsUserView2");
    }

    /**
     * Container's getter for AccAccountingView4.
     * @return AccAccountingView4
     */
    public ViewObjectImpl getAccAccountingView4() {
        return (ViewObjectImpl)findViewObject("AccAccountingView4");
    }

    /**
     * Container's getter for AccAccountingOstView4.
     * @return AccAccountingOstView4
     */
    public ViewObjectImpl getAccAccountingOstView4() {
        return (ViewObjectImpl)findViewObject("AccAccountingOstView4");
    }

    /**
     * Container's getter for AccAccountingView5.
     * @return AccAccountingView5
     */
    public ViewObjectImpl getAccAccountingView5() {
        return (ViewObjectImpl)findViewObject("AccAccountingView5");
    }

    /**
     * Container's getter for AccFinancialResultView3.
     * @return AccFinancialResultView3
     */
    public ViewObjectImpl getAccFinancialResultView3() {
        return (ViewObjectImpl)findViewObject("AccFinancialResultView3");
    }

    /**
     * Container's getter for DostavkaTabPartOrdersView3.
     * @return DostavkaTabPartOrdersView3
     */
    public ViewObjectImpl getDostavkaTabPartOrdersView3() {
        return (ViewObjectImpl)findViewObject("DostavkaTabPartOrdersView3");
    }

    /**
     * Container's getter for AccCostView4.
     * @return AccCostView4
     */
    public ViewObjectImpl getAccCostView4() {
        return (ViewObjectImpl)findViewObject("AccCostView4");
    }

    /**
     * Container's getter for OrdersView2.
     * @return OrdersView2
     */
    public ViewObjectImpl getOrdersView2() {
        return (ViewObjectImpl)findViewObject("OrdersView2");
    }

    /**
     * Container's getter for OrdersView3.
     * @return OrdersView3
     */
    public ViewObjectImpl getOrdersView3() {
        return (ViewObjectImpl)findViewObject("OrdersView3");
    }

    /**
     * Container's getter for OrdersView4.
     * @return OrdersView4
     */
    public ViewObjectImpl getOrdersView4() {
        return (ViewObjectImpl)findViewObject("OrdersView4");
    }

    /**
     * Container's getter for OrdersTabPartOplatyView2.
     * @return OrdersTabPartOplatyView2
     */
    public ViewObjectImpl getOrdersTabPartOplatyView2() {
        return (ViewObjectImpl)findViewObject("OrdersTabPartOplatyView2");
    }

    /**
     * Container's getter for OrdersTabPartZatratyView2.
     * @return OrdersTabPartZatratyView2
     */
    public ViewObjectImpl getOrdersTabPartZatratyView2() {
        return (ViewObjectImpl)findViewObject("OrdersTabPartZatratyView2");
    }

    /**
     * Container's getter for AccZatrView3.
     * @return AccZatrView3
     */
    public ViewObjectImpl getAccZatrView3() {
        return (ViewObjectImpl)findViewObject("AccZatrView3");
    }

    /**
     * Container's getter for OtherZatratyView2.
     * @return OtherZatratyView2
     */
    public OtherZatratyViewImpl getOtherZatratyView2() {
        return (OtherZatratyViewImpl)findViewObject("OtherZatratyView2");
    }

    /**
     * Container's getter for OtherZatratyTabPartZatratyView2.
     * @return OtherZatratyTabPartZatratyView2
     */
    public ViewObjectImpl getOtherZatratyTabPartZatratyView2() {
        return (ViewObjectImpl)findViewObject("OtherZatratyTabPartZatratyView2");
    }

    /**
     * Container's getter for ScalesZatratView2.
     * @return ScalesZatratView2
     */
    public ScalesZatratViewImpl getScalesZatratView2() {
        return (ScalesZatratViewImpl)findViewObject("ScalesZatratView2");
    }

    /**
     * Container's getter for DostavkaView5.
     * @return DostavkaView5
     */
    public DostavkaViewImpl getDostavkaView5() {
        return (DostavkaViewImpl)findViewObject("DostavkaView5");
    }

    /**
     * Container's getter for OtherZatratyView3.
     * @return OtherZatratyView3
     */
    public OtherZatratyViewImpl getOtherZatratyView3() {
        return (OtherZatratyViewImpl)findViewObject("OtherZatratyView3");
    }

    /**
     * Container's getter for ScalesZatratView3.
     * @return ScalesZatratView3
     */
    public ScalesZatratViewImpl getScalesZatratView3() {
        return (ScalesZatratViewImpl)findViewObject("ScalesZatratView3");
    }

    /**
     * Container's getter for OrdersView5.
     * @return OrdersView5
     */
    public ViewObjectImpl getOrdersView5() {
        return (ViewObjectImpl)findViewObject("OrdersView5");
    }

    /**
     * Container's getter for DivisionsView3.
     * @return DivisionsView3
     */
    public DivisionsViewImpl getDivisionsView3() {
        return (DivisionsViewImpl)findViewObject("DivisionsView3");
    }

    /**
     * Container's getter for KontragentsUserView3.
     * @return KontragentsUserView3
     */
    public ViewObjectImpl getKontragentsUserView3() {
        return (ViewObjectImpl)findViewObject("KontragentsUserView3");
    }

    /**
     * Container's getter for DivisionsSotrView3.
     * @return DivisionsSotrView3
     */
    public ViewObjectImpl getDivisionsSotrView3() {
        return (ViewObjectImpl)findViewObject("DivisionsSotrView3");
    }

    /**
     * Container's getter for AccCostView5.
     * @return AccCostView5
     */
    public ViewObjectImpl getAccCostView5() {
        return (ViewObjectImpl)findViewObject("AccCostView5");
    }

    /**
     * Container's getter for UsersView2.
     * @return UsersView2
     */
    public ViewObjectImpl getUsersView2() {
        return (ViewObjectImpl)findViewObject("UsersView2");
    }

    /**
     * Container's getter for UserSettingsView2.
     * @return UserSettingsView2
     */
    public UserSettingsViewImpl getUserSettingsView2() {
        return (UserSettingsViewImpl)findViewObject("UserSettingsView2");
    }

    /**
     * Container's getter for UserSettingsView3.
     * @return UserSettingsView3
     */
    public UserSettingsViewImpl getUserSettingsView3() {
        return (UserSettingsViewImpl)findViewObject("UserSettingsView3");
    }

    /**
     * Container's getter for UserSettingsView4.
     * @return UserSettingsView4
     */
    public UserSettingsViewImpl getUserSettingsView4() {
        return (UserSettingsViewImpl)findViewObject("UserSettingsView4");
    }

    /**
     * Container's getter for UserTabPartContactsView2.
     * @return UserTabPartContactsView2
     */
    public ViewObjectImpl getUserTabPartContactsView2() {
        return (ViewObjectImpl)findViewObject("UserTabPartContactsView2");
    }

    /**
     * Container's getter for ScalesZatratView4.
     * @return ScalesZatratView4
     */
    public ScalesZatratViewImpl getScalesZatratView4() {
        return (ScalesZatratViewImpl)findViewObject("ScalesZatratView4");
    }

    /**
     * Container's getter for AccZatrView4.
     * @return AccZatrView4
     */
    public ViewObjectImpl getAccZatrView4() {
        return (ViewObjectImpl)findViewObject("AccZatrView4");
    }

    /**
     * Container's getter for ZatratyView2.
     * @return ZatratyView2
     */
    public ViewObjectImpl getZatratyView2() {
        return (ViewObjectImpl)findViewObject("ZatratyView2");
    }

    /**
     * Container's getter for OrdersTabPartZatratyView3.
     * @return OrdersTabPartZatratyView3
     */
    public ViewObjectImpl getOrdersTabPartZatratyView3() {
        return (ViewObjectImpl)findViewObject("OrdersTabPartZatratyView3");
    }

    /**
     * Container's getter for OtherZatratyTabPartZatratyView3.
     * @return OtherZatratyTabPartZatratyView3
     */
    public ViewObjectImpl getOtherZatratyTabPartZatratyView3() {
        return (ViewObjectImpl)findViewObject("OtherZatratyTabPartZatratyView3");
    }

    /**
     * Container's getter for AccCostView6.
     * @return AccCostView6
     */
    public ViewObjectImpl getAccCostView6() {
        return (ViewObjectImpl)findViewObject("AccCostView6");
    }

    /**
     * Container's getter for ZatratyView3.
     * @return ZatratyView3
     */
    public ViewObjectImpl getZatratyView3() {
        return (ViewObjectImpl)findViewObject("ZatratyView3");
    }

    /**
     * Container's getter for VwOrderView1.
     * @return VwOrderView1
     */
    public VwOrderViewImpl getVwOrderView1() {
        return (VwOrderViewImpl)findViewObject("VwOrderView1");
    }

    /**
     * Container's getter for OrdersTabPartOplatyView3.
     * @return OrdersTabPartOplatyView3
     */
    public ViewObjectImpl getOrdersTabPartOplatyView3() {
        return (ViewObjectImpl)findViewObject("OrdersTabPartOplatyView3");
    }

    /**
     * Container's getter for AccCostView7.
     * @return AccCostView7
     */
    public ViewObjectImpl getAccCostView7() {
        return (ViewObjectImpl)findViewObject("AccCostView7");
    }

    /**
     * Container's getter for VwTurnoverWeekView1.
     * @return VwTurnoverWeekView1
     */
    public ViewObjectImpl getVwTurnoverWeekView1() {
        return (ViewObjectImpl)findViewObject("VwTurnoverWeekView1");
    }

    /**
     * Container's getter for VwUdevordersView1.
     * @return VwUdevordersView1
     */
    public ViewObjectImpl getVwUdevordersView1() {
        return (ViewObjectImpl)findViewObject("VwUdevordersView1");
    }

    /**
     * Container's getter for DolgKontragents1.
     * @return DolgKontragents1
     */
    public DolgKontragentsImpl getDolgKontragents1() {
        return (DolgKontragentsImpl)findViewObject("DolgKontragents1");
    }

    /**
     * Container's getter for VwScalesView1.
     * @return VwScalesView1
     */
    public VwScalesViewImpl getVwScalesView1() {
        return (VwScalesViewImpl)findViewObject("VwScalesView1");
    }

    /**
     * Container's getter for ZatratyPostView1.
     * @return ZatratyPostView1
     */
    public ZatratyPostViewImpl getZatratyPostView1() {
        return (ZatratyPostViewImpl)findViewObject("ZatratyPostView1");
    }

    /**
     * Container's getter for ZatratyPostView2.
     * @return ZatratyPostView2
     */
    public ZatratyPostViewImpl getZatratyPostView2() {
        return (ZatratyPostViewImpl)findViewObject("ZatratyPostView2");
    }

    /**
     * Container's getter for ZatratyPostView3.
     * @return ZatratyPostView3
     */
    public ZatratyPostViewImpl getZatratyPostView3() {
        return (ZatratyPostViewImpl)findViewObject("ZatratyPostView3");
    }

    /**
     * Container's getter for MenuView1.
     * @return MenuView1
     */
    public ViewObjectImpl getMenuView1() {
        return (ViewObjectImpl)findViewObject("MenuView1");
    }

    /**
     * Container's getter for MenuView2.
     * @return MenuView2
     */
    public ViewObjectImpl getMenuView2() {
        return (ViewObjectImpl)findViewObject("MenuView2");
    }

    /**
     * Container's getter for VwZatratyPerMonthView1.
     * @return VwZatratyPerMonthView1
     */
    public VwZatratyPerMonthViewImpl getVwZatratyPerMonthView1() {
        return (VwZatratyPerMonthViewImpl)findViewObject("VwZatratyPerMonthView1");
    }

    /**
     * Container's getter for VwZatratyPerMonthView2.
     * @return VwZatratyPerMonthView2
     */
    public VwZatratyPerMonthViewImpl getVwZatratyPerMonthView2() {
        return (VwZatratyPerMonthViewImpl)findViewObject("VwZatratyPerMonthView2");
    }

    /**
     * Container's getter for ReportsView1.
     * @return ReportsView1
     */
    public ViewObjectImpl getReportsView1() {
        return (ViewObjectImpl)findViewObject("ReportsView1");
    }

    /**
     * Container's getter for VwZatratyPerMonthView3.
     * @return VwZatratyPerMonthView3
     */
    public VwZatratyPerMonthViewImpl getVwZatratyPerMonthView3() {
        return (VwZatratyPerMonthViewImpl)findViewObject("VwZatratyPerMonthView3");
    }

    /**
     * Container's getter for VwSalesPerMonthView1.
     * @return VwSalesPerMonthView1
     */
    public VwSalesPerMonthViewImpl getVwSalesPerMonthView1() {
        return (VwSalesPerMonthViewImpl)findViewObject("VwSalesPerMonthView1");
    }

    /**
     * Container's getter for VwSalesPerMonthView2.
     * @return VwSalesPerMonthView2
     */
    public VwSalesPerMonthViewImpl getVwSalesPerMonthView2() {
        return (VwSalesPerMonthViewImpl)findViewObject("VwSalesPerMonthView2");
    }

    /**
     * Container's getter for VwSalesPerMonthView3.
     * @return VwSalesPerMonthView3
     */
    public VwSalesPerMonthViewImpl getVwSalesPerMonthView3() {
        return (VwSalesPerMonthViewImpl)findViewObject("VwSalesPerMonthView3");
    }

    /**
     * Container's getter for ReportViewSalesPerMonth1.
     * @return ReportViewSalesPerMonth1
     */
    public ViewObjectImpl getReportViewSalesPerMonth1() {
        return (ViewObjectImpl)findViewObject("ReportViewSalesPerMonth1");
    }

    /**
     * Container's getter for VwSalesPerMonthView4.
     * @return VwSalesPerMonthView4
     */
    public VwSalesPerMonthViewImpl getVwSalesPerMonthView4() {
        return (VwSalesPerMonthViewImpl)findViewObject("VwSalesPerMonthView4");
    }

    /**
     * Container's getter for VwSalesReportView1.
     * @return VwSalesReportView1
     */
    public VwSalesReportViewImpl getVwSalesReportView1() {
        return (VwSalesReportViewImpl)findViewObject("VwSalesReportView1");
    }

    /**
     * Container's getter for RegistrationTableView1.
     * @return RegistrationTableView1
     */
    public ViewObjectImpl getRegistrationTableView1() {
        return (ViewObjectImpl)findViewObject("RegistrationTableView1");
    }

    /**
     * Container's getter for RegistrationTableView2.
     * @return RegistrationTableView2
     */
    public ViewObjectImpl getRegistrationTableView2() {
        return (ViewObjectImpl)findViewObject("RegistrationTableView2");
    }

    /**
     * Container's getter for CatalogMetaTablesView1.
     * @return CatalogMetaTablesView1
     */
    public CatalogMetaTablesViewImpl getCatalogMetaTablesView1() {
        return (CatalogMetaTablesViewImpl)findViewObject("CatalogMetaTablesView1");
    }

    /**
     * Container's getter for CatalogMetaInsTableView1.
     * @return CatalogMetaInsTableView1
     */
    public ViewObjectImpl getCatalogMetaInsTableView1() {
        return (ViewObjectImpl)findViewObject("CatalogMetaInsTableView1");
    }

    /**
     * Container's getter for CatalogMetaInsTableView2.
     * @return CatalogMetaInsTableView2
     */
    public ViewObjectImpl getCatalogMetaInsTableView2() {
        return (ViewObjectImpl)findViewObject("CatalogMetaInsTableView2");
    }

    /**
     * Container's getter for CatalogMetaUpdTableView1.
     * @return CatalogMetaUpdTableView1
     */
    public ViewObjectImpl getCatalogMetaUpdTableView1() {
        return (ViewObjectImpl)findViewObject("CatalogMetaUpdTableView1");
    }

    /**
     * Container's getter for CatalogMetaUpdTableView2.
     * @return CatalogMetaUpdTableView2
     */
    public ViewObjectImpl getCatalogMetaUpdTableView2() {
        return (ViewObjectImpl)findViewObject("CatalogMetaUpdTableView2");
    }

    /**
     * Container's getter for CatalogMetaXmlTableView1.
     * @return CatalogMetaXmlTableView1
     */
    public ViewObjectImpl getCatalogMetaXmlTableView1() {
        return (ViewObjectImpl)findViewObject("CatalogMetaXmlTableView1");
    }

    /**
     * Container's getter for CatalogMetaXmlTableView2.
     * @return CatalogMetaXmlTableView2
     */
    public ViewObjectImpl getCatalogMetaXmlTableView2() {
        return (ViewObjectImpl)findViewObject("CatalogMetaXmlTableView2");
    }

    /**
     * Container's getter for UsersAllView1.
     * @return UsersAllView1
     */
    public ViewObjectImpl getUsersAllView1() {
        return (ViewObjectImpl)findViewObject("UsersAllView1");
    }

    /**
     * Container's getter for OplataIschodView1.
     * @return OplataIschodView1
     */
    public OplataIschodViewImpl getOplataIschodView1() {
        return (OplataIschodViewImpl)findViewObject("OplataIschodView1");
    }

    /**
     * Container's getter for OplataIschodTabPartView1.
     * @return OplataIschodTabPartView1
     */
    public ViewObjectImpl getOplataIschodTabPartView1() {
        return (ViewObjectImpl)findViewObject("OplataIschodTabPartView1");
    }

    /**
     * Container's getter for OplataIschodTabPartView2.
     * @return OplataIschodTabPartView2
     */
    public ViewObjectImpl getOplataIschodTabPartView2() {
        return (ViewObjectImpl)findViewObject("OplataIschodTabPartView2");
    }

    /**
     * Container's getter for OplataIschodView2.
     * @return OplataIschodView2
     */
    public OplataIschodViewImpl getOplataIschodView2() {
        return (OplataIschodViewImpl)findViewObject("OplataIschodView2");
    }

    /**
     * Container's getter for OplataIschodView3.
     * @return OplataIschodView3
     */
    public OplataIschodViewImpl getOplataIschodView3() {
        return (OplataIschodViewImpl)findViewObject("OplataIschodView3");
    }

    /**
     * Container's getter for OplataIschodView4.
     * @return OplataIschodView4
     */
    public OplataIschodViewImpl getOplataIschodView4() {
        return (OplataIschodViewImpl)findViewObject("OplataIschodView4");
    }

    /**
     * Container's getter for OplataIschodTabPartView3.
     * @return OplataIschodTabPartView3
     */
    public ViewObjectImpl getOplataIschodTabPartView3() {
        return (ViewObjectImpl)findViewObject("OplataIschodTabPartView3");
    }

    /**
     * Container's getter for OplataIschodView5.
     * @return OplataIschodView5
     */
    public OplataIschodViewImpl getOplataIschodView5() {
        return (OplataIschodViewImpl)findViewObject("OplataIschodView5");
    }

    /**
     * Container's getter for KonsultNameView1.
     * @return KonsultNameView1
     */
    public KonsultNameViewImpl getKonsultNameView1() {
        return (KonsultNameViewImpl)findViewObject("KonsultNameView1");
    }

    /**
     * Container's getter for KonsultNameView2.
     * @return KonsultNameView2
     */
    public KonsultNameViewImpl getKonsultNameView2() {
        return (KonsultNameViewImpl)findViewObject("KonsultNameView2");
    }

    /**
     * Container's getter for AccAccountingOstCurrenFk1Link1.
     * @return AccAccountingOstCurrenFk1Link1
     */
    public ViewLinkImpl getAccAccountingOstCurrenFk1Link1() {
        return (ViewLinkImpl)findViewLink("AccAccountingOstCurrenFk1Link1");
    }

    /**
     * Container's getter for AccAccountingCurrencyFk1Link1.
     * @return AccAccountingCurrencyFk1Link1
     */
    public ViewLinkImpl getAccAccountingCurrencyFk1Link1() {
        return (ViewLinkImpl)findViewLink("AccAccountingCurrencyFk1Link1");
    }

    /**
     * Container's getter for AccZatrDivisionsFk1Link1.
     * @return AccZatrDivisionsFk1Link1
     */
    public ViewLinkImpl getAccZatrDivisionsFk1Link1() {
        return (ViewLinkImpl)findViewLink("AccZatrDivisionsFk1Link1");
    }

    /**
     * Container's getter for DivisionsDivisionsFk1Link1.
     * @return DivisionsDivisionsFk1Link1
     */
    public ViewLinkImpl getDivisionsDivisionsFk1Link1() {
        return (ViewLinkImpl)findViewLink("DivisionsDivisionsFk1Link1");
    }

    /**
     * Container's getter for AccCostDivisionsFk1Link1.
     * @return AccCostDivisionsFk1Link1
     */
    public ViewLinkImpl getAccCostDivisionsFk1Link1() {
        return (ViewLinkImpl)findViewLink("AccCostDivisionsFk1Link1");
    }

    /**
     * Container's getter for DivisionSotrDivisionsFk1Link1.
     * @return DivisionSotrDivisionsFk1Link1
     */
    public ViewLinkImpl getDivisionSotrDivisionsFk1Link1() {
        return (ViewLinkImpl)findViewLink("DivisionSotrDivisionsFk1Link1");
    }

    /**
     * Container's getter for DostavkaBaseOfClassifiFk1Link1.
     * @return DostavkaBaseOfClassifiFk1Link1
     */
    public ViewLinkImpl getDostavkaBaseOfClassifiFk1Link1() {
        return (ViewLinkImpl)findViewLink("DostavkaBaseOfClassifiFk1Link1");
    }

    /**
     * Container's getter for DostavkaCurrencyFk1Link1.
     * @return DostavkaCurrencyFk1Link1
     */
    public ViewLinkImpl getDostavkaCurrencyFk1Link1() {
        return (ViewLinkImpl)findViewLink("DostavkaCurrencyFk1Link1");
    }

    /**
     * Container's getter for DostavkaDivisionsFk1Link1.
     * @return DostavkaDivisionsFk1Link1
     */
    public ViewLinkImpl getDostavkaDivisionsFk1Link1() {
        return (ViewLinkImpl)findViewLink("DostavkaDivisionsFk1Link1");
    }

    /**
     * Container's getter for DostavkaTabPartOrdersFk1Link1.
     * @return DostavkaTabPartOrdersFk1Link1
     */
    public ViewLinkImpl getDostavkaTabPartOrdersFk1Link1() {
        return (ViewLinkImpl)findViewLink("DostavkaTabPartOrdersFk1Link1");
    }

    /**
     * Container's getter for KassaCurrencyFk1Link1.
     * @return KassaCurrencyFk1Link1
     */
    public ViewLinkImpl getKassaCurrencyFk1Link1() {
        return (ViewLinkImpl)findViewLink("KassaCurrencyFk1Link1");
    }

    /**
     * Container's getter for KassaDivisionsFk1Link1.
     * @return KassaDivisionsFk1Link1
     */
    public ViewLinkImpl getKassaDivisionsFk1Link1() {
        return (ViewLinkImpl)findViewLink("KassaDivisionsFk1Link1");
    }

    /**
     * Container's getter for AccAccountingOstKontraFk1Link1.
     * @return AccAccountingOstKontraFk1Link1
     */
    public ViewLinkImpl getAccAccountingOstKontraFk1Link1() {
        return (ViewLinkImpl)findViewLink("AccAccountingOstKontraFk1Link1");
    }

    /**
     * Container's getter for AccAccountingKontragentFk1Link1.
     * @return AccAccountingKontragentFk1Link1
     */
    public ViewLinkImpl getAccAccountingKontragentFk1Link1() {
        return (ViewLinkImpl)findViewLink("AccAccountingKontragentFk1Link1");
    }

    /**
     * Container's getter for AccFinancialResultKontFk1Link1.
     * @return AccFinancialResultKontFk1Link1
     */
    public ViewLinkImpl getAccFinancialResultKontFk1Link1() {
        return (ViewLinkImpl)findViewLink("AccFinancialResultKontFk1Link1");
    }

    /**
     * Container's getter for KontragentsKontragentsFk1Link1.
     * @return KontragentsKontragentsFk1Link1
     */
    public ViewLinkImpl getKontragentsKontragentsFk1Link1() {
        return (ViewLinkImpl)findViewLink("KontragentsKontragentsFk1Link1");
    }

    /**
     * Container's getter for AccCostKontragentsFk1Link1.
     * @return AccCostKontragentsFk1Link1
     */
    public ViewLinkImpl getAccCostKontragentsFk1Link1() {
        return (ViewLinkImpl)findViewLink("AccCostKontragentsFk1Link1");
    }

    /**
     * Container's getter for KontragentsUserKontrageFk1Link1.
     * @return KontragentsUserKontrageFk1Link1
     */
    public ViewLinkImpl getKontragentsUserKontrageFk1Link1() {
        return (ViewLinkImpl)findViewLink("KontragentsUserKontrageFk1Link1");
    }

    /**
     * Container's getter for AccAccountingMoveStatFk1Link1.
     * @return AccAccountingMoveStatFk1Link1
     */
    public ViewLinkImpl getAccAccountingMoveStatFk1Link1() {
        return (ViewLinkImpl)findViewLink("AccAccountingMoveStatFk1Link1");
    }

    /**
     * Container's getter for AccAccountingOstOrdersFk1Link1.
     * @return AccAccountingOstOrdersFk1Link1
     */
    public ViewLinkImpl getAccAccountingOstOrdersFk1Link1() {
        return (ViewLinkImpl)findViewLink("AccAccountingOstOrdersFk1Link1");
    }

    /**
     * Container's getter for AccAccountingOrdersFk1Link1.
     * @return AccAccountingOrdersFk1Link1
     */
    public ViewLinkImpl getAccAccountingOrdersFk1Link1() {
        return (ViewLinkImpl)findViewLink("AccAccountingOrdersFk1Link1");
    }

    /**
     * Container's getter for AccFinancialResultOrdeFk1Link1.
     * @return AccFinancialResultOrdeFk1Link1
     */
    public ViewLinkImpl getAccFinancialResultOrdeFk1Link1() {
        return (ViewLinkImpl)findViewLink("AccFinancialResultOrdeFk1Link1");
    }

    /**
     * Container's getter for DostavkaTabPartOrdersFk2Link1.
     * @return DostavkaTabPartOrdersFk2Link1
     */
    public ViewLinkImpl getDostavkaTabPartOrdersFk2Link1() {
        return (ViewLinkImpl)findViewLink("DostavkaTabPartOrdersFk2Link1");
    }

    /**
     * Container's getter for AccCostOrdersFk1Link1.
     * @return AccCostOrdersFk1Link1
     */
    public ViewLinkImpl getAccCostOrdersFk1Link1() {
        return (ViewLinkImpl)findViewLink("AccCostOrdersFk1Link1");
    }

    /**
     * Container's getter for OrdersDivisionsFk1Link1.
     * @return OrdersDivisionsFk1Link1
     */
    public ViewLinkImpl getOrdersDivisionsFk1Link1() {
        return (ViewLinkImpl)findViewLink("OrdersDivisionsFk1Link1");
    }

    /**
     * Container's getter for OrdersKassaFk1Link1.
     * @return OrdersKassaFk1Link1
     */
    public ViewLinkImpl getOrdersKassaFk1Link1() {
        return (ViewLinkImpl)findViewLink("OrdersKassaFk1Link1");
    }

    /**
     * Container's getter for OrdersKontragentsFk1Link1.
     * @return OrdersKontragentsFk1Link1
     */
    public ViewLinkImpl getOrdersKontragentsFk1Link1() {
        return (ViewLinkImpl)findViewLink("OrdersKontragentsFk1Link1");
    }

    /**
     * Container's getter for OrdersTabPartOplatyOrFk1Link1.
     * @return OrdersTabPartOplatyOrFk1Link1
     */
    public ViewLinkImpl getOrdersTabPartOplatyOrFk1Link1() {
        return (ViewLinkImpl)findViewLink("OrdersTabPartOplatyOrFk1Link1");
    }

    /**
     * Container's getter for OrdersTabPartZatratyOFk1Link1.
     * @return OrdersTabPartZatratyOFk1Link1
     */
    public ViewLinkImpl getOrdersTabPartZatratyOFk1Link1() {
        return (ViewLinkImpl)findViewLink("OrdersTabPartZatratyOFk1Link1");
    }

    /**
     * Container's getter for AccZatrOtherZatratyFk1Link1.
     * @return AccZatrOtherZatratyFk1Link1
     */
    public ViewLinkImpl getAccZatrOtherZatratyFk1Link1() {
        return (ViewLinkImpl)findViewLink("AccZatrOtherZatratyFk1Link1");
    }

    /**
     * Container's getter for OtherZatratyDivisionsFk1Link1.
     * @return OtherZatratyDivisionsFk1Link1
     */
    public ViewLinkImpl getOtherZatratyDivisionsFk1Link1() {
        return (ViewLinkImpl)findViewLink("OtherZatratyDivisionsFk1Link1");
    }

    /**
     * Container's getter for OtherZatratyTabPartZaFk1Link1.
     * @return OtherZatratyTabPartZaFk1Link1
     */
    public ViewLinkImpl getOtherZatratyTabPartZaFk1Link1() {
        return (ViewLinkImpl)findViewLink("OtherZatratyTabPartZaFk1Link1");
    }

    /**
     * Container's getter for ScalesZatratBaseOfCalFk1Link1.
     * @return ScalesZatratBaseOfCalFk1Link1
     */
    public ViewLinkImpl getScalesZatratBaseOfCalFk1Link1() {
        return (ViewLinkImpl)findViewLink("ScalesZatratBaseOfCalFk1Link1");
    }

    /**
     * Container's getter for DostavkaUsersFk1Link1.
     * @return DostavkaUsersFk1Link1
     */
    public ViewLinkImpl getDostavkaUsersFk1Link1() {
        return (ViewLinkImpl)findViewLink("DostavkaUsersFk1Link1");
    }

    /**
     * Container's getter for OtherZatratyUsersFk1Link1.
     * @return OtherZatratyUsersFk1Link1
     */
    public ViewLinkImpl getOtherZatratyUsersFk1Link1() {
        return (ViewLinkImpl)findViewLink("OtherZatratyUsersFk1Link1");
    }

    /**
     * Container's getter for ScalesZatratUsersFk1Link1.
     * @return ScalesZatratUsersFk1Link1
     */
    public ViewLinkImpl getScalesZatratUsersFk1Link1() {
        return (ViewLinkImpl)findViewLink("ScalesZatratUsersFk1Link1");
    }

    /**
     * Container's getter for OrdersUsersFk1Link1.
     * @return OrdersUsersFk1Link1
     */
    public ViewLinkImpl getOrdersUsersFk1Link1() {
        return (ViewLinkImpl)findViewLink("OrdersUsersFk1Link1");
    }

    /**
     * Container's getter for DivisionsUsersFk1Link1.
     * @return DivisionsUsersFk1Link1
     */
    public ViewLinkImpl getDivisionsUsersFk1Link1() {
        return (ViewLinkImpl)findViewLink("DivisionsUsersFk1Link1");
    }

    /**
     * Container's getter for KontragentsUserUsersFk1Link1.
     * @return KontragentsUserUsersFk1Link1
     */
    public ViewLinkImpl getKontragentsUserUsersFk1Link1() {
        return (ViewLinkImpl)findViewLink("KontragentsUserUsersFk1Link1");
    }

    /**
     * Container's getter for DivisionSotrUsersFk1Link1.
     * @return DivisionSotrUsersFk1Link1
     */
    public ViewLinkImpl getDivisionSotrUsersFk1Link1() {
        return (ViewLinkImpl)findViewLink("DivisionSotrUsersFk1Link1");
    }

    /**
     * Container's getter for AccCostUsersFk1Link1.
     * @return AccCostUsersFk1Link1
     */
    public ViewLinkImpl getAccCostUsersFk1Link1() {
        return (ViewLinkImpl)findViewLink("AccCostUsersFk1Link1");
    }

    /**
     * Container's getter for UsersRoleFk1Link1.
     * @return UsersRoleFk1Link1
     */
    public ViewLinkImpl getUsersRoleFk1Link1() {
        return (ViewLinkImpl)findViewLink("UsersRoleFk1Link1");
    }

    /**
     * Container's getter for UserSettingsDivisionsFk1Link1.
     * @return UserSettingsDivisionsFk1Link1
     */
    public ViewLinkImpl getUserSettingsDivisionsFk1Link1() {
        return (ViewLinkImpl)findViewLink("UserSettingsDivisionsFk1Link1");
    }

    /**
     * Container's getter for UserSettingsKassaFk1Link1.
     * @return UserSettingsKassaFk1Link1
     */
    public ViewLinkImpl getUserSettingsKassaFk1Link1() {
        return (ViewLinkImpl)findViewLink("UserSettingsKassaFk1Link1");
    }

    /**
     * Container's getter for UserSettingsUsersFk1Link1.
     * @return UserSettingsUsersFk1Link1
     */
    public ViewLinkImpl getUserSettingsUsersFk1Link1() {
        return (ViewLinkImpl)findViewLink("UserSettingsUsersFk1Link1");
    }

    /**
     * Container's getter for UserTabPartContactsUsFk1Link1.
     * @return UserTabPartContactsUsFk1Link1
     */
    public ViewLinkImpl getUserTabPartContactsUsFk1Link1() {
        return (ViewLinkImpl)findViewLink("UserTabPartContactsUsFk1Link1");
    }

    /**
     * Container's getter for ScalesZatratZatratyFk1Link1.
     * @return ScalesZatratZatratyFk1Link1
     */
    public ViewLinkImpl getScalesZatratZatratyFk1Link1() {
        return (ViewLinkImpl)findViewLink("ScalesZatratZatratyFk1Link1");
    }

    /**
     * Container's getter for AccZatrZatratyFk1Link1.
     * @return AccZatrZatratyFk1Link1
     */
    public ViewLinkImpl getAccZatrZatratyFk1Link1() {
        return (ViewLinkImpl)findViewLink("AccZatrZatratyFk1Link1");
    }

    /**
     * Container's getter for ZatratyZatratyFk1Link1.
     * @return ZatratyZatratyFk1Link1
     */
    public ViewLinkImpl getZatratyZatratyFk1Link1() {
        return (ViewLinkImpl)findViewLink("ZatratyZatratyFk1Link1");
    }

    /**
     * Container's getter for OrdersTabPartZatratyZFk1Link1.
     * @return OrdersTabPartZatratyZFk1Link1
     */
    public ViewLinkImpl getOrdersTabPartZatratyZFk1Link1() {
        return (ViewLinkImpl)findViewLink("OrdersTabPartZatratyZFk1Link1");
    }

    /**
     * Container's getter for OtherZatratyTabPartZaFk2Link1.
     * @return OtherZatratyTabPartZaFk2Link1
     */
    public ViewLinkImpl getOtherZatratyTabPartZaFk2Link1() {
        return (ViewLinkImpl)findViewLink("OtherZatratyTabPartZaFk2Link1");
    }

    /**
     * Container's getter for AccCostZatratyFk1Link1.
     * @return AccCostZatratyFk1Link1
     */
    public ViewLinkImpl getAccCostZatratyFk1Link1() {
        return (ViewLinkImpl)findViewLink("AccCostZatratyFk1Link1");
    }

    /**
     * Container's getter for ZatratyKontragentsFk1Link1.
     * @return ZatratyKontragentsFk1Link1
     */
    public ViewLinkImpl getZatratyKontragentsFk1Link1() {
        return (ViewLinkImpl)findViewLink("ZatratyKontragentsFk1Link1");
    }

    /**
     * Container's getter for VwOrderOplatyFkLink1.
     * @return VwOrderOplatyFkLink1
     */
    public ViewLinkImpl getVwOrderOplatyFkLink1() {
        return (ViewLinkImpl)findViewLink("VwOrderOplatyFkLink1");
    }

    /**
     * Container's getter for VwOrderAccCostFkLink1.
     * @return VwOrderAccCostFkLink1
     */
    public ViewLinkImpl getVwOrderAccCostFkLink1() {
        return (ViewLinkImpl)findViewLink("VwOrderAccCostFkLink1");
    }

    /**
     * Container's getter for ZatratyPostParentFnLink1.
     * @return ZatratyPostParentFnLink1
     */
    public ViewLinkImpl getZatratyPostParentFnLink1() {
        return (ViewLinkImpl)findViewLink("ZatratyPostParentFnLink1");
    }

    /**
     * Container's getter for OtherZatratyTPZatratyPostFkLink1.
     * @return OtherZatratyTPZatratyPostFkLink1
     */
    public ViewLinkImpl getOtherZatratyTPZatratyPostFkLink1() {
        return (ViewLinkImpl)findViewLink("OtherZatratyTPZatratyPostFkLink1");
    }

    /**
     * Container's getter for MenuMenuFk1Link1.
     * @return MenuMenuFk1Link1
     */
    public ViewLinkImpl getMenuMenuFk1Link1() {
        return (ViewLinkImpl)findViewLink("MenuMenuFk1Link1");
    }

    /**
     * Container's getter for VwZatratyMonthDivisionFkLink1.
     * @return VwZatratyMonthDivisionFkLink1
     */
    public ViewLinkImpl getVwZatratyMonthDivisionFkLink1() {
        return (ViewLinkImpl)findViewLink("VwZatratyMonthDivisionFkLink1");
    }

    /**
     * Container's getter for ReportVwZatratyPerMonthFkLink1.
     * @return ReportVwZatratyPerMonthFkLink1
     */
    public ViewLinkImpl getReportVwZatratyPerMonthFkLink1() {
        return (ViewLinkImpl)findViewLink("ReportVwZatratyPerMonthFkLink1");
    }

    /**
     * Container's getter for VwSalesMonthDivisionFkLink1.
     * @return VwSalesMonthDivisionFkLink1
     */
    public ViewLinkImpl getVwSalesMonthDivisionFkLink1() {
        return (ViewLinkImpl)findViewLink("VwSalesMonthDivisionFkLink1");
    }

    /**
     * Container's getter for ReportVwSalesPerMonthFkLink1.
     * @return ReportVwSalesPerMonthFkLink1
     */
    public ViewLinkImpl getReportVwSalesPerMonthFkLink1() {
        return (ViewLinkImpl)findViewLink("ReportVwSalesPerMonthFkLink1");
    }

    /**
     * Container's getter for ReportSummarySalesPerMonthLink1.
     * @return ReportSummarySalesPerMonthLink1
     */
    public ViewLinkImpl getReportSummarySalesPerMonthLink1() {
        return (ViewLinkImpl)findViewLink("ReportSummarySalesPerMonthLink1");
    }

    /**
     * Container's getter for RegistrationTableFk1Link1.
     * @return RegistrationTableFk1Link1
     */
    public ViewLinkImpl getRegistrationTableFk1Link1() {
        return (ViewLinkImpl)findViewLink("RegistrationTableFk1Link1");
    }

    /**
     * Container's getter for CatalogMetaInsTableCaFk1Link1.
     * @return CatalogMetaInsTableCaFk1Link1
     */
    public ViewLinkImpl getCatalogMetaInsTableCaFk1Link1() {
        return (ViewLinkImpl)findViewLink("CatalogMetaInsTableCaFk1Link1");
    }

    /**
     * Container's getter for CatalogMetaUpdTableCaFk1Link1.
     * @return CatalogMetaUpdTableCaFk1Link1
     */
    public ViewLinkImpl getCatalogMetaUpdTableCaFk1Link1() {
        return (ViewLinkImpl)findViewLink("CatalogMetaUpdTableCaFk1Link1");
    }

    /**
     * Container's getter for CatalogMetaXmlTableFk1Link1.
     * @return CatalogMetaXmlTableFk1Link1
     */
    public ViewLinkImpl getCatalogMetaXmlTableFk1Link1() {
        return (ViewLinkImpl)findViewLink("CatalogMetaXmlTableFk1Link1");
    }

    /**
     * Container's getter for OplataIschodTabPartOpFk1Link1.
     * @return OplataIschodTabPartOpFk1Link1
     */
    public ViewLinkImpl getOplataIschodTabPartOpFk1Link1() {
        return (ViewLinkImpl)findViewLink("OplataIschodTabPartOpFk1Link1");
    }

    /**
     * Container's getter for OplataIschodFk3Link1.
     * @return OplataIschodFk3Link1
     */
    public ViewLinkImpl getOplataIschodFk3Link1() {
        return (ViewLinkImpl)findViewLink("OplataIschodFk3Link1");
    }

    /**
     * Container's getter for OplataIschodFk5Link1.
     * @return OplataIschodFk5Link1
     */
    public ViewLinkImpl getOplataIschodFk5Link1() {
        return (ViewLinkImpl)findViewLink("OplataIschodFk5Link1");
    }

    /**
     * Container's getter for OplataIschodFk1Link1.
     * @return OplataIschodFk1Link1
     */
    public ViewLinkImpl getOplataIschodFk1Link1() {
        return (ViewLinkImpl)findViewLink("OplataIschodFk1Link1");
    }

    /**
     * Container's getter for OplataIschodTabPartOrFk1Link1.
     * @return OplataIschodTabPartOrFk1Link1
     */
    public ViewLinkImpl getOplataIschodTabPartOrFk1Link1() {
        return (ViewLinkImpl)findViewLink("OplataIschodTabPartOrFk1Link1");
    }

    /**
     * Container's getter for OplataIschodFk4Link1.
     * @return OplataIschodFk4Link1
     */
    public ViewLinkImpl getOplataIschodFk4Link1() {
        return (ViewLinkImpl)findViewLink("OplataIschodFk4Link1");
    }

    /**
     * Container's getter for KonsultNameDivisionsFk1Link1.
     * @return KonsultNameDivisionsFk1Link1
     */
    public ViewLinkImpl getKonsultNameDivisionsFk1Link1() {
        return (ViewLinkImpl)findViewLink("KonsultNameDivisionsFk1Link1");
    }

    /**
     * Container's getter for MontagNameView1.
     * @return MontagNameView1
     */
    public MontagNameViewImpl getMontagNameView1() {
        return (MontagNameViewImpl)findViewObject("MontagNameView1");
    }

    /**
     * Container's getter for MontagNameView2.
     * @return MontagNameView2
     */
    public MontagNameViewImpl getMontagNameView2() {
        return (MontagNameViewImpl)findViewObject("MontagNameView2");
    }

    /**
     * Container's getter for MontagNameDivisionsFk1Link1.
     * @return MontagNameDivisionsFk1Link1
     */
    public ViewLinkImpl getMontagNameDivisionsFk1Link1() {
        return (ViewLinkImpl)findViewLink("MontagNameDivisionsFk1Link1");
    }

    /**
     * Container's getter for ZamerNameView1.
     * @return ZamerNameView1
     */
    public ZamerNameViewImpl getZamerNameView1() {
        return (ZamerNameViewImpl)findViewObject("ZamerNameView1");
    }

    /**
     * Container's getter for ZamerNameView2.
     * @return ZamerNameView2
     */
    public ZamerNameViewImpl getZamerNameView2() {
        return (ZamerNameViewImpl)findViewObject("ZamerNameView2");
    }

    /**
     * Container's getter for ZamerNameDivisionsFk1Link1.
     * @return ZamerNameDivisionsFk1Link1
     */
    public ViewLinkImpl getZamerNameDivisionsFk1Link1() {
        return (ViewLinkImpl)findViewLink("ZamerNameDivisionsFk1Link1");
    }

    /**
     * Container's getter for AccCurrencyView1.
     * @return AccCurrencyView1
     */
    public ViewObjectImpl getAccCurrencyView1() {
        return (ViewObjectImpl)findViewObject("AccCurrencyView1");
    }

    /**
     * Container's getter for AccCurrencyView2.
     * @return AccCurrencyView2
     */
    public ViewObjectImpl getAccCurrencyView2() {
        return (ViewObjectImpl)findViewObject("AccCurrencyView2");
    }

    /**
     * Container's getter for AccCurrencyCurrencyFk1Link1.
     * @return AccCurrencyCurrencyFk1Link1
     */
    public ViewLinkImpl getAccCurrencyCurrencyFk1Link1() {
        return (ViewLinkImpl)findViewLink("AccCurrencyCurrencyFk1Link1");
    }

    /**
     * Container's getter for AccCurrencyView3.
     * @return AccCurrencyView3
     */
    public ViewObjectImpl getAccCurrencyView3() {
        return (ViewObjectImpl)findViewObject("AccCurrencyView3");
    }

    /**
     * Container's getter for AccCurrencyKassaFk1Link1.
     * @return AccCurrencyKassaFk1Link1
     */
    public ViewLinkImpl getAccCurrencyKassaFk1Link1() {
        return (ViewLinkImpl)findViewLink("AccCurrencyKassaFk1Link1");
    }

    /**
     * Container's getter for AccCurDivView1.
     * @return AccCurDivView1
     */
    public ViewObjectImpl getAccCurDivView1() {
        return (ViewObjectImpl)findViewObject("AccCurDivView1");
    }

    /**
     * Container's getter for AccCurDivView2.
     * @return AccCurDivView2
     */
    public ViewObjectImpl getAccCurDivView2() {
        return (ViewObjectImpl)findViewObject("AccCurDivView2");
    }

    /**
     * Container's getter for AccCurDivDivisionsFkLink1.
     * @return AccCurDivDivisionsFkLink1
     */
    public ViewLinkImpl getAccCurDivDivisionsFkLink1() {
        return (ViewLinkImpl)findViewLink("AccCurDivDivisionsFkLink1");
    }

    /**
     * Container's getter for AccDebetDivView1.
     * @return AccDebetDivView1
     */
    public ViewObjectImpl getAccDebetDivView1() {
        return (ViewObjectImpl)findViewObject("AccDebetDivView1");
    }

    /**
     * Container's getter for AccDebetDivView2.
     * @return AccDebetDivView2
     */
    public ViewObjectImpl getAccDebetDivView2() {
        return (ViewObjectImpl)findViewObject("AccDebetDivView2");
    }

    /**
     * Container's getter for AccDebetDivisionsFnLink1.
     * @return AccDebetDivisionsFnLink1
     */
    public ViewLinkImpl getAccDebetDivisionsFnLink1() {
        return (ViewLinkImpl)findViewLink("AccDebetDivisionsFnLink1");
    }

    /**
     * Container's getter for VwBepView1.
     * @return VwBepView1
     */
    public ViewObjectImpl getVwBepView1() {
        return (ViewObjectImpl)findViewObject("VwBepView1");
    }

    /**
     * Container's getter for VwBepView2.
     * @return VwBepView2
     */
    public ViewObjectImpl getVwBepView2() {
        return (ViewObjectImpl)findViewObject("VwBepView2");
    }

    /**
     * Container's getter for VwBepDivisionsFkLink1.
     * @return VwBepDivisionsFkLink1
     */
    public ViewLinkImpl getVwBepDivisionsFkLink1() {
        return (ViewLinkImpl)findViewLink("VwBepDivisionsFkLink1");
    }

    /**
     * Container's getter for AccFizView1.
     * @return AccFizView1
     */
    public ViewObjectImpl getAccFizView1() {
        return (ViewObjectImpl)findViewObject("AccFizView1");
    }

    /**
     * Container's getter for AccFizView2.
     * @return AccFizView2
     */
    public ViewObjectImpl getAccFizView2() {
        return (ViewObjectImpl)findViewObject("AccFizView2");
    }

    /**
     * Container's getter for AccFizCurrencyFkLink1.
     * @return AccFizCurrencyFkLink1
     */
    public ViewLinkImpl getAccFizCurrencyFkLink1() {
        return (ViewLinkImpl)findViewLink("AccFizCurrencyFkLink1");
    }

    /**
     * Container's getter for AccFizView3.
     * @return AccFizView3
     */
    public ViewObjectImpl getAccFizView3() {
        return (ViewObjectImpl)findViewObject("AccFizView3");
    }

    /**
     * Container's getter for AccFizKontragentsFkLink1.
     * @return AccFizKontragentsFkLink1
     */
    public ViewLinkImpl getAccFizKontragentsFkLink1() {
        return (ViewLinkImpl)findViewLink("AccFizKontragentsFkLink1");
    }

    /**
     * Container's getter for AccFizView4.
     * @return AccFizView4
     */
    public ViewObjectImpl getAccFizView4() {
        return (ViewObjectImpl)findViewObject("AccFizView4");
    }

    /**
     * Container's getter for AccFizMoveStatFkLink1.
     * @return AccFizMoveStatFkLink1
     */
    public ViewLinkImpl getAccFizMoveStatFkLink1() {
        return (ViewLinkImpl)findViewLink("AccFizMoveStatFkLink1");
    }

    /**
     * Container's getter for AccFizDolgView1.
     * @return AccFizDolgView1
     */
    public AccFizDolgViewImpl getAccFizDolgView1() {
        return (AccFizDolgViewImpl)findViewObject("AccFizDolgView1");
    }

    /**
     * Container's getter for AccFizView5.
     * @return AccFizView5
     */
    public ViewObjectImpl getAccFizView5() {
        return (ViewObjectImpl)findViewObject("AccFizView5");
    }

    /**
     * Container's getter for AccFizDolgAccFizFkLink1.
     * @return AccFizDolgAccFizFkLink1
     */
    public ViewLinkImpl getAccFizDolgAccFizFkLink1() {
        return (ViewLinkImpl)findViewLink("AccFizDolgAccFizFkLink1");
    }

    /**
     * Container's getter for KonsultNameActiveView1.
     * @return KonsultNameActiveView1
     */
    public KonsultNameActiveViewImpl getKonsultNameActiveView1() {
        return (KonsultNameActiveViewImpl)findViewObject("KonsultNameActiveView1");
    }

    /**
     * Container's getter for MontagNameActive1.
     * @return MontagNameActive1
     */
    public MontagNameActiveImpl getMontagNameActive1() {
        return (MontagNameActiveImpl)findViewObject("MontagNameActive1");
    }

    /**
     * Container's getter for ZamerNameViewActive1.
     * @return ZamerNameViewActive1
     */
    public ZamerNameViewActiveImpl getZamerNameViewActive1() {
        return (ZamerNameViewActiveImpl)findViewObject("ZamerNameViewActive1");
    }

    /**
     * Container's getter for SessionsView1.
     * @return SessionsView1
     */
    public ViewObjectImpl getSessionsView1() {
        return (ViewObjectImpl)findViewObject("SessionsView1");
    }
}
