package falcon.app_module.server.serviceinterface;

import falcon.app_module.AppModuleImpl;
import falcon.app_module.common.serviceinterface.FalconService;

import falcon.view.common.VwBepViewSDO;
import falcon.view.common.VwOrderViewSDO;

import java.lang.reflect.Method;

import java.math.BigDecimal;

import java.util.List;

import javax.ejb.Remote;
import javax.ejb.Stateless;

import javax.interceptor.Interceptors;

import oracle.jbo.common.Diagnostic;
import oracle.jbo.common.sdo.SDOHelper;
import oracle.jbo.common.service.types.FindControl;
import oracle.jbo.common.service.types.FindCriteria;
import oracle.jbo.server.svc.ServiceContextInterceptor;
import oracle.jbo.server.svc.ServiceImpl;
import oracle.jbo.service.errors.ServiceException;

import oracle.webservices.annotations.ManagementPolicy;
import oracle.webservices.annotations.PortableWebService;
import oracle.webservices.annotations.ReliabilityPolicy;
import oracle.webservices.annotations.SecurityPolicy;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat May 24 13:31:33 EEST 2014
// ---------------------------------------------------------------------
@Interceptors( { ServiceContextInterceptor.class })
@SecurityPolicy( { "oracle/wss_http_token_service_policy" })
@Stateless(name="falcon.app_module.common.FalconServiceBean", mappedName="FalconServiceBean")
@Remote(FalconService.class)
@PortableWebService(targetNamespace="/falcon/app_module/common/", serviceName="FalconService", portName="FalconServiceSoapHttpPort",
    endpointInterface="falcon.app_module.common.serviceinterface.FalconService")
public class FalconServiceImpl extends ServiceImpl implements FalconService {
    private static boolean _isInited = false;

    /**
     * This is the default constructor (do not remove).
     */
    public FalconServiceImpl() {
        init();
        setApplicationModuleDefName("falcon.app_module.AppModule");
        setConfigurationName("FalconService");
    }


    /**
     * Generated method. Do not modify. Do initialization in the constructor
     */
    protected void init() {
        if (_isInited) {
            return;
        }
        synchronized (FalconServiceImpl.class) {
            if (_isInited) {
                return;
            }
            try {
                SDOHelper.INSTANCE.defineSchema("falcon/app_module/common/serviceinterface/", "FalconService.xsd");
                _isInited = true;
            } catch (Exception ex) {
                Diagnostic.printStackTrace(ex);
            }
        }
    }


    /**
     * getVwOrderView1: generated method. Do not modify.
     */
    public VwOrderViewSDO getVwOrderView1(BigDecimal id) throws ServiceException {
        return (VwOrderViewSDO)get(new Object[] { id }, "VwOrderView1", VwOrderViewSDO.class);
    }

    /**
     * updateVwOrderView1: generated method. Do not modify.
     */
    public VwOrderViewSDO updateVwOrderView1(VwOrderViewSDO vwOrderView1) throws ServiceException {
        return (VwOrderViewSDO)update(vwOrderView1, "VwOrderView1");
    }

    /**
     * createVwOrderView1: generated method. Do not modify.
     */
    public VwOrderViewSDO createVwOrderView1(VwOrderViewSDO vwOrderView1) throws ServiceException {
        return (VwOrderViewSDO)create(vwOrderView1, "VwOrderView1");
    }

    /**
     * findVwOrderView1: generated method. Do not modify.
     */
    public List<VwOrderViewSDO> findVwOrderView1(FindCriteria findCriteria,
                                                 FindControl findControl) throws ServiceException {
        return (List<VwOrderViewSDO>)find(findCriteria, findControl, "VwOrderView1", VwOrderViewSDO.class);
    }
}
