package falcon.view.common;

import oracle.jbo.Row;
import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 11 19:42:43 EET 2012
// ---------------------------------------------------------------------
public interface CatalogMetaTablesView extends ViewObject {
    String getRowStatus(Row row);
}
