package falcon.view.common;

import java.math.BigDecimal;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Dec 09 17:59:24 EET 2012
// ---------------------------------------------------------------------
public interface ObmenSettingsView extends ViewObject {
    void doSynchronization(BigDecimal id);
}
