package falcon.view.common;

import oracle.jbo.ViewObject;
import oracle.jbo.domain.Date;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jan 29 16:45:03 EET 2014
// ---------------------------------------------------------------------
public interface VwBepView extends ViewObject {
    Date getu_dat();
}
