package falcon.view.common;

import oracle.jbo.Row;
import oracle.jbo.ViewObject;
import oracle.jbo.domain.Date;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 23 15:31:26 EET 2012
// ---------------------------------------------------------------------
public interface VwOrderView extends ViewObject {
    String getRowStatus(Row row);

    void setf_dat(Date value);

    void setl_dat(Date value);
}
