package falcon.view.common;

import oracle.jbo.ViewObject;
import oracle.jbo.domain.Date;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jan 25 19:48:09 EET 2014
// ---------------------------------------------------------------------
public interface VwSalesReportView extends ViewObject {
    void setu_dat(Date value);
}
