package falcon.view.common;

import oracle.jbo.ViewObject;
import oracle.jbo.domain.Date;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jan 25 19:55:43 EET 2014
// ---------------------------------------------------------------------
public interface VwSalesPerMonthView extends ViewObject {
    void setu_dat(Date value);

    void setu_name(String value);
}
