package falcon.view.common;

import oracle.jbo.ViewObject;
import oracle.jbo.domain.Date;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jan 26 14:04:33 EET 2014
// ---------------------------------------------------------------------
public interface VwZatratyPerMonthView extends ViewObject {
    void setu_dat(Date value);
}
