package falcon.view.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 20 18:52:32 EET 2014
// ---------------------------------------------------------------------
public interface ZamerNameLookupVO extends ViewObject {
    void setSearchCriteria(String value);
}
