package falcon.view.common;

import java.math.BigDecimal;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Dec 10 20:54:27 EET 2012
// ---------------------------------------------------------------------
public interface ZatratyPostView extends ViewObject {
    void createZatratyArticle(BigDecimal id_par, String za);
}
