package falcon.app_module.common.serviceinterface;

import falcon.view.common.VwBepViewSDO;
import falcon.view.common.VwOrderViewSDO;

import java.math.BigDecimal;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.soap.SOAPBinding;

import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import oracle.jbo.common.service.types.FindControl;
import oracle.jbo.common.service.types.FindCriteria;
import oracle.jbo.service.errors.ServiceException;

import oracle.webservices.annotations.PortableWebService;
import oracle.webservices.annotations.SDODatabinding;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat May 24 13:31:33 EEST 2014
// ---------------------------------------------------------------------
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.WRAPPED, style = SOAPBinding.Style.DOCUMENT)
@PortableWebService(targetNamespace="/falcon/app_module/common/", name="FalconService", wsdlLocation="falcon/app_module/common/serviceinterface/FalconService.wsdl")
@SDODatabinding(schemaLocation="falcon/app_module/common/serviceinterface/FalconService.xsd")
public interface FalconService {


    public static final String NAME = "{/falcon/app_module/common/}FalconService";


    @WebMethod(action="/falcon/app_module/common/getVwOrderView1", operationName="getVwOrderView1")
    @RequestWrapper(targetNamespace="/falcon/app_module/common/types/", localName="getVwOrderView1")
    @ResponseWrapper(targetNamespace="/falcon/app_module/common/types/", localName="getVwOrderView1Response")
    @WebResult(name="result")
    VwOrderViewSDO getVwOrderView1(@WebParam(mode = WebParam.Mode.IN, name="id")
        BigDecimal id) throws ServiceException;

    @WebMethod(action="/falcon/app_module/common/updateVwOrderView1", operationName="updateVwOrderView1")
    @RequestWrapper(targetNamespace="/falcon/app_module/common/types/", localName="updateVwOrderView1")
    @ResponseWrapper(targetNamespace="/falcon/app_module/common/types/", localName="updateVwOrderView1Response")
    @WebResult(name="result")
    VwOrderViewSDO updateVwOrderView1(@WebParam(mode = WebParam.Mode.IN, name="vwOrderView1")
        VwOrderViewSDO vwOrderView1) throws ServiceException;

    @WebMethod(action="/falcon/app_module/common/createVwOrderView1", operationName="createVwOrderView1")
    @RequestWrapper(targetNamespace="/falcon/app_module/common/types/", localName="createVwOrderView1")
    @ResponseWrapper(targetNamespace="/falcon/app_module/common/types/", localName="createVwOrderView1Response")
    @WebResult(name="result")
    VwOrderViewSDO createVwOrderView1(@WebParam(mode = WebParam.Mode.IN, name="vwOrderView1")
        VwOrderViewSDO vwOrderView1) throws ServiceException;

    @WebMethod(action="/falcon/app_module/common/findVwOrderView1", operationName="findVwOrderView1")
    @RequestWrapper(targetNamespace="/falcon/app_module/common/types/", localName="findVwOrderView1")
    @ResponseWrapper(targetNamespace="/falcon/app_module/common/types/", localName="findVwOrderView1Response")
    @WebResult(name="result")
    List<VwOrderViewSDO> findVwOrderView1(@WebParam(mode = WebParam.Mode.IN, name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;
}
