package falcon.view;

import falcon.view.common.CatalogMetaTablesView;

import oracle.jbo.Row;
import oracle.jbo.server.Entity;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 11 19:40:53 EET 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CatalogMetaTablesViewImpl extends ViewObjectImpl implements CatalogMetaTablesView {
    /**
     * This is the default constructor (do not remove).
     */
    public CatalogMetaTablesViewImpl() {
    }
    
    public String getRowStatus(Row row) {
        CatalogMetaTablesViewRowImpl rwImpl = (CatalogMetaTablesViewRowImpl)row;
        String rwStatus = translateStatusToString(rwImpl.getEntity(0).getEntityState());
        return rwStatus;
    }
    
    private String translateStatusToString(byte b) {
        String ret = null;
        switch (b) {
        case Entity.STATUS_INITIALIZED:
            {
                ret = "Initialized";
                break;
            }
        case Entity.STATUS_MODIFIED:
            {
                ret = "Modified";
                break;
            }
        case Entity.STATUS_UNMODIFIED:
            {
                ret = "Unmodified";
                break;
            }
        case Entity.STATUS_NEW:
            {
                ret = "New";
                break;
            }
        }
        return ret;
    }

}
