package falcon.view;


import falcon.view.common.ObmenSettingsView;

import java.math.BigDecimal;

import model.FalconFiltersViewObjectImpl;

import oracle.jbo.Row;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Dec 09 17:27:12 EET 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ObmenSettingsViewImpl extends FalconFiltersViewObjectImpl implements ObmenSettingsView {
    /**
     * This is the default constructor (do not remove).
     */
    public ObmenSettingsViewImpl() {
    }

    public void doSynchronization(BigDecimal id) {
        callStoredProcedure("INTERCHANGE.SYNC(?)", new Object[] { id });

    }
}
