package falcon.view;

import model.FalconFiltersViewObjectImpl;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 29 19:11:20 EET 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OplataIschodViewImpl extends FalconFiltersViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public OplataIschodViewImpl() {
    }

    /**
     * Returns the bind variable value for u_name.
     * @return bind variable value for u_name
     */
     public String getu_name() {
         //return (String)getNamedWhereClauseParam("u_name");
         return getSessionUserName();
     }

    /**
     * Sets <code>value</code> for bind variable u_name.
     * @param value value to bind as u_name
     */
    public void setu_name(String value) {
        setNamedWhereClauseParam("u_name", value);
    }
}
