package falcon.view;

import java.math.BigDecimal;

import model.FalconFiltersViewObjectImpl;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 22 12:46:30 EET 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ScalesZatratViewImpl extends FalconFiltersViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ScalesZatratViewImpl() {
    }

    /**
     * Returns the bind variable value for id_user.
     * @return bind variable value for id_user
     */
    public BigDecimal getid_user() {
        //return (BigDecimal)getNamedWhereClauseParam("id_user");
        return getSessionUserId();
    }

    /**
     * Sets <code>value</code> for bind variable id_user.
     * @param value value to bind as id_user
     */
    public void setid_user(BigDecimal value) {
        setNamedWhereClauseParam("id_user", value);
    }
}
