package falcon.view;

import java.math.BigDecimal;

import model.FalconFiltersViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 21 14:14:22 EET 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UserSettingsViewImpl extends FalconFiltersViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public UserSettingsViewImpl() {
    }
    
    /**
     * Returns the bind variable value for id_user.
     * @return bind variable value for id_user
     */
    public BigDecimal getid_user() {
        //return (Number)getNamedWhereClauseParam("id_user");
        return getSessionUserId();
        
    }

    /**
     * Sets <code>value</code> for bind variable id_user.
     * @param value value to bind as id_user
     */
    public void setid_user(BigDecimal value) {
        setNamedWhereClauseParam("id_user", value);
    }
}
