package falcon.view;

import falcon.view.common.VwBepView;

import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jan 29 16:41:07 EET 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VwBepViewImpl extends ViewObjectImpl implements VwBepView {
    /**
     * This is the default constructor (do not remove).
     */
    public VwBepViewImpl() {
    }

    /**
     * Returns the bind variable value for u_dat.
     * @return bind variable value for u_dat
     */
    public Date getu_dat() {
        return (Date)getNamedWhereClauseParam("u_dat");
    }

    /**
     * Sets <code>value</code> for bind variable u_dat.
     * @param value value to bind as u_dat
     */
    public void setu_dat(Date value) {
        setNamedWhereClauseParam("u_dat", value);
    }
}
