package falcon.view;

import falcon.entity.VwOrderImpl;

import java.math.BigDecimal;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 19 12:44:14 EET 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VwOrderViewRowImpl extends ViewRowImpl {


    public static final int ENTITY_VWORDER = 0;

    public EntityImpl getOrders() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        Id {
            public Object get(VwOrderViewRowImpl obj) {
                return obj.getId();
            }

            public void put(VwOrderViewRowImpl obj, Object value) {
                obj.setId((BigDecimal)value);
            }
        }
        ,
        Num {
            public Object get(VwOrderViewRowImpl obj) {
                return obj.getNum();
            }

            public void put(VwOrderViewRowImpl obj, Object value) {
                obj.setNum((String)value);
            }
        }
        ,
        Dat {
            public Object get(VwOrderViewRowImpl obj) {
                return obj.getDat();
            }

            public void put(VwOrderViewRowImpl obj, Object value) {
                obj.setDat((Timestamp)value);
            }
        }
        ,
        Kontrag {
            public Object get(VwOrderViewRowImpl obj) {
                return obj.getKontrag();
            }

            public void put(VwOrderViewRowImpl obj, Object value) {
                obj.setKontrag((String)value);
            }
        }
        ,
        UserS {
            public Object get(VwOrderViewRowImpl obj) {
                return obj.getUserS();
            }

            public void put(VwOrderViewRowImpl obj, Object value) {
                obj.setUserS((String)value);
            }
        }
        ,
        Division {
            public Object get(VwOrderViewRowImpl obj) {
                return obj.getDivision();
            }

            public void put(VwOrderViewRowImpl obj, Object value) {
                obj.setDivision((String)value);
            }
        }
        ,
        Kassa {
            public Object get(VwOrderViewRowImpl obj) {
                return obj.getKassa();
            }

            public void put(VwOrderViewRowImpl obj, Object value) {
                obj.setKassa((String)value);
            }
        }
        ,
        Kredit {
            public Object get(VwOrderViewRowImpl obj) {
                return obj.getKredit();
            }

            public void put(VwOrderViewRowImpl obj, Object value) {
                obj.setKredit((Integer)value);
            }
        }
        ,
        Metrag {
            public Object get(VwOrderViewRowImpl obj) {
                return obj.getMetrag();
            }

            public void put(VwOrderViewRowImpl obj, Object value) {
                obj.setMetrag((BigDecimal)value);
            }
        }
        ,
        Summa {
            public Object get(VwOrderViewRowImpl obj) {
                return obj.getSumma();
            }

            public void put(VwOrderViewRowImpl obj, Object value) {
                obj.setSumma((BigDecimal)value);
            }
        }
        ,
        ZakSumm {
            public Object get(VwOrderViewRowImpl obj) {
                return obj.getZakSumm();
            }

            public void put(VwOrderViewRowImpl obj, Object value) {
                obj.setZakSumm((BigDecimal)value);
            }
        }
        ,
        DolgKlienta {
            public Object get(VwOrderViewRowImpl obj) {
                return obj.getDolgKlienta();
            }

            public void put(VwOrderViewRowImpl obj, Object value) {
                obj.setDolgKlienta((BigDecimal)value);
            }
        }
        ,
        Zamer {
            public Object get(VwOrderViewRowImpl obj) {
                return obj.getZamer();
            }

            public void put(VwOrderViewRowImpl obj, Object value) {
                obj.setZamer((BigDecimal)value);
            }
        }
        ,
        Konsult {
            public Object get(VwOrderViewRowImpl obj) {
                return obj.getKonsult();
            }

            public void put(VwOrderViewRowImpl obj, Object value) {
                obj.setKonsult((BigDecimal)value);
            }
        }
        ,
        Montag {
            public Object get(VwOrderViewRowImpl obj) {
                return obj.getMontag();
            }

            public void put(VwOrderViewRowImpl obj, Object value) {
                obj.setMontag((BigDecimal)value);
            }
        }
        ,
        Dostavka {
            public Object get(VwOrderViewRowImpl obj) {
                return obj.getDostavka();
            }

            public void put(VwOrderViewRowImpl obj, Object value) {
                obj.setDostavka((BigDecimal)value);
            }
        }
        ,
        Bank {
            public Object get(VwOrderViewRowImpl obj) {
                return obj.getBank();
            }

            public void put(VwOrderViewRowImpl obj, Object value) {
                obj.setBank((BigDecimal)value);
            }
        }
        ,
        KonsultName {
            public Object get(VwOrderViewRowImpl obj) {
                return obj.getKonsultName();
            }

            public void put(VwOrderViewRowImpl obj, Object value) {
                obj.setKonsultName((String)value);
            }
        }
        ,
        MontagName {
            public Object get(VwOrderViewRowImpl obj) {
                return obj.getMontagName();
            }

            public void put(VwOrderViewRowImpl obj, Object value) {
                obj.setMontagName((String)value);
            }
        }
        ,
        ZamerName {
            public Object get(VwOrderViewRowImpl obj) {
                return obj.getZamerName();
            }

            public void put(VwOrderViewRowImpl obj, Object value) {
                obj.setZamerName((String)value);
            }
        }
        ,
        Returned {
            public Object get(VwOrderViewRowImpl obj) {
                return obj.getReturned();
            }

            public void put(VwOrderViewRowImpl obj, Object value) {
                obj.setReturned((Integer)value);
            }
        }
        ,
        KonsulrId {
            public Object get(VwOrderViewRowImpl obj) {
                return obj.getKonsulrId();
            }

            public void put(VwOrderViewRowImpl obj, Object value) {
                obj.setKonsulrId((BigDecimal)value);
            }
        }
        ,
        MontagId {
            public Object get(VwOrderViewRowImpl obj) {
                return obj.getMontagId();
            }

            public void put(VwOrderViewRowImpl obj, Object value) {
                obj.setMontagId((BigDecimal)value);
            }
        }
        ,
        ZamerId {
            public Object get(VwOrderViewRowImpl obj) {
                return obj.getZamerId();
            }

            public void put(VwOrderViewRowImpl obj, Object value) {
                obj.setZamerId((BigDecimal)value);
            }
        }
        ,
        Total_Cost {
            public Object get(VwOrderViewRowImpl obj) {
                return obj.getTotal_Cost();
            }

            public void put(VwOrderViewRowImpl obj, Object value) {
                obj.setTotal_Cost((Number)value);
            }
        }
        ,
        Total_Summa {
            public Object get(VwOrderViewRowImpl obj) {
                return obj.getTotal_Summa();
            }

            public void put(VwOrderViewRowImpl obj, Object value) {
                obj.setTotal_Summa((Number)value);
            }
        }
        ,
        KreditBoolean {
            public Object get(VwOrderViewRowImpl obj) {
                return obj.getKreditBoolean();
            }

            public void put(VwOrderViewRowImpl obj, Object value) {
                obj.setKreditBoolean((Boolean)value);
            }
        }
        ,
        OrdersTabPartOplatyView {
            public Object get(VwOrderViewRowImpl obj) {
                return obj.getOrdersTabPartOplatyView();
            }

            public void put(VwOrderViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        AccCostView {
            public Object get(VwOrderViewRowImpl obj) {
                return obj.getAccCostView();
            }

            public void put(VwOrderViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        KonsultNameView1 {
            public Object get(VwOrderViewRowImpl obj) {
                return obj.getKonsultNameView1();
            }

            public void put(VwOrderViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        VwOrderView1 {
            public Object get(VwOrderViewRowImpl obj) {
                return obj.getVwOrderView1();
            }

            public void put(VwOrderViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MontagNameView1 {
            public Object get(VwOrderViewRowImpl obj) {
                return obj.getMontagNameView1();
            }

            public void put(VwOrderViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ZamerNameView1 {
            public Object get(VwOrderViewRowImpl obj) {
                return obj.getZamerNameView1();
            }

            public void put(VwOrderViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(VwOrderViewRowImpl object);

        public abstract void put(VwOrderViewRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ID = AttributesEnum.Id.index();
    public static final int NUM = AttributesEnum.Num.index();
    public static final int DAT = AttributesEnum.Dat.index();
    public static final int KONTRAG = AttributesEnum.Kontrag.index();
    public static final int USERS = AttributesEnum.UserS.index();
    public static final int DIVISION = AttributesEnum.Division.index();
    public static final int KASSA = AttributesEnum.Kassa.index();
    public static final int KREDIT = AttributesEnum.Kredit.index();
    public static final int METRAG = AttributesEnum.Metrag.index();
    public static final int SUMMA = AttributesEnum.Summa.index();
    public static final int ZAKSUMM = AttributesEnum.ZakSumm.index();
    public static final int DOLGKLIENTA = AttributesEnum.DolgKlienta.index();
    public static final int ZAMER = AttributesEnum.Zamer.index();
    public static final int KONSULT = AttributesEnum.Konsult.index();
    public static final int MONTAG = AttributesEnum.Montag.index();
    public static final int DOSTAVKA = AttributesEnum.Dostavka.index();
    public static final int BANK = AttributesEnum.Bank.index();
    public static final int KONSULTNAME = AttributesEnum.KonsultName.index();
    public static final int MONTAGNAME = AttributesEnum.MontagName.index();
    public static final int ZAMERNAME = AttributesEnum.ZamerName.index();
    public static final int RETURNED = AttributesEnum.Returned.index();
    public static final int KONSULRID = AttributesEnum.KonsulrId.index();
    public static final int MONTAGID = AttributesEnum.MontagId.index();
    public static final int ZAMERID = AttributesEnum.ZamerId.index();
    public static final int TOTAL_COST = AttributesEnum.Total_Cost.index();
    public static final int TOTAL_SUMMA = AttributesEnum.Total_Summa.index();
    public static final int KREDITBOOLEAN = AttributesEnum.KreditBoolean.index();
    public static final int ORDERSTABPARTOPLATYVIEW = AttributesEnum.OrdersTabPartOplatyView.index();
    public static final int ACCCOSTVIEW = AttributesEnum.AccCostView.index();
    public static final int KONSULTNAMEVIEW1 = AttributesEnum.KonsultNameView1.index();
    public static final int VWORDERVIEW1 = AttributesEnum.VwOrderView1.index();
    public static final int MONTAGNAMEVIEW1 = AttributesEnum.MontagNameView1.index();
    public static final int ZAMERNAMEVIEW1 = AttributesEnum.ZamerNameView1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public VwOrderViewRowImpl() {
    }

    /**
     * Gets VwOrder entity object.
     * @return the VwOrder
     */
    public VwOrderImpl getVwOrder() {
        return (VwOrderImpl)getEntity(ENTITY_VWORDER);
    }

    /**
     * Gets the attribute value for ID using the alias name Id.
     * @return the ID
     */
    public BigDecimal getId() {
        return (BigDecimal) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as attribute value for ID using the alias name Id.
     * @param value value to set the ID
     */
    public void setId(BigDecimal value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for NUM using the alias name Num.
     * @return the NUM
     */
    public String getNum() {
        return (String) getAttributeInternal(NUM);
    }

    /**
     * Sets <code>value</code> as attribute value for NUM using the alias name Num.
     * @param value value to set the NUM
     */
    public void setNum(String value) {
        setAttributeInternal(NUM, value);
    }

    /**
     * Gets the attribute value for DAT using the alias name Dat.
     * @return the DAT
     */
    public Timestamp getDat() {
        return (Timestamp) getAttributeInternal(DAT);
    }

    /**
     * Sets <code>value</code> as attribute value for DAT using the alias name Dat.
     * @param value value to set the DAT
     */
    public void setDat(Timestamp value) {
        setAttributeInternal(DAT, value);
    }

    /**
     * Gets the attribute value for KONTRAG using the alias name Kontrag.
     * @return the KONTRAG
     */
    public String getKontrag() {
        return (String) getAttributeInternal(KONTRAG);
    }

    /**
     * Sets <code>value</code> as attribute value for KONTRAG using the alias name Kontrag.
     * @param value value to set the KONTRAG
     */
    public void setKontrag(String value) {
        setAttributeInternal(KONTRAG, value);
    }

    /**
     * Gets the attribute value for USER_S using the alias name UserS.
     * @return the USER_S
     */
    public String getUserS() {
        return (String) getAttributeInternal(USERS);
    }

    /**
     * Sets <code>value</code> as attribute value for USER_S using the alias name UserS.
     * @param value value to set the USER_S
     */
    public void setUserS(String value) {
        setAttributeInternal(USERS, value);
    }

    /**
     * Gets the attribute value for DIVISION using the alias name Division.
     * @return the DIVISION
     */
    public String getDivision() {
        return (String) getAttributeInternal(DIVISION);
    }

    /**
     * Sets <code>value</code> as attribute value for DIVISION using the alias name Division.
     * @param value value to set the DIVISION
     */
    public void setDivision(String value) {
        setAttributeInternal(DIVISION, value);
    }

    /**
     * Gets the attribute value for KASSA using the alias name Kassa.
     * @return the KASSA
     */
    public String getKassa() {
        return (String) getAttributeInternal(KASSA);
    }

    /**
     * Sets <code>value</code> as attribute value for KASSA using the alias name Kassa.
     * @param value value to set the KASSA
     */
    public void setKassa(String value) {
        setAttributeInternal(KASSA, value);
    }

    /**
     * Gets the attribute value for KREDIT using the alias name Kredit.
     * @return the KREDIT
     */
    public Integer getKredit() {
        return (Integer) getAttributeInternal(KREDIT);
    }

    /**
     * Sets <code>value</code> as attribute value for KREDIT using the alias name Kredit.
     * @param value value to set the KREDIT
     */
    public void setKredit(Integer value) {
        setAttributeInternal(KREDIT, value);
    }

    /**
     * Gets the attribute value for METRAG using the alias name Metrag.
     * @return the METRAG
     */
    public BigDecimal getMetrag() {
        return (BigDecimal) getAttributeInternal(METRAG);
    }

    /**
     * Sets <code>value</code> as attribute value for METRAG using the alias name Metrag.
     * @param value value to set the METRAG
     */
    public void setMetrag(BigDecimal value) {
        setAttributeInternal(METRAG, value);
    }

    /**
     * Gets the attribute value for SUMMA using the alias name Summa.
     * @return the SUMMA
     */
    public BigDecimal getSumma() {
        return (BigDecimal) getAttributeInternal(SUMMA);
    }

    /**
     * Sets <code>value</code> as attribute value for SUMMA using the alias name Summa.
     * @param value value to set the SUMMA
     */
    public void setSumma(BigDecimal value) {
        setAttributeInternal(SUMMA, value);
    }

    /**
     * Gets the attribute value for ZAK_SUMM using the alias name ZakSumm.
     * @return the ZAK_SUMM
     */
    public BigDecimal getZakSumm() {
        return (BigDecimal) getAttributeInternal(ZAKSUMM);
    }

    /**
     * Sets <code>value</code> as attribute value for ZAK_SUMM using the alias name ZakSumm.
     * @param value value to set the ZAK_SUMM
     */
    public void setZakSumm(BigDecimal value) {
        setAttributeInternal(ZAKSUMM, value);
    }

    /**
     * Gets the attribute value for DOLG_KLIENTA using the alias name DolgKlienta.
     * @return the DOLG_KLIENTA
     */
    public BigDecimal getDolgKlienta() {
        return (BigDecimal) getAttributeInternal(DOLGKLIENTA);
    }

    /**
     * Sets <code>value</code> as attribute value for DOLG_KLIENTA using the alias name DolgKlienta.
     * @param value value to set the DOLG_KLIENTA
     */
    public void setDolgKlienta(BigDecimal value) {
        setAttributeInternal(DOLGKLIENTA, value);
    }

    /**
     * Gets the attribute value for ZAMER using the alias name Zamer.
     * @return the ZAMER
     */
    public BigDecimal getZamer() {
        return (BigDecimal) getAttributeInternal(ZAMER);
    }

    /**
     * Sets <code>value</code> as attribute value for ZAMER using the alias name Zamer.
     * @param value value to set the ZAMER
     */
    public void setZamer(BigDecimal value) {
        setAttributeInternal(ZAMER, value);
    }

    /**
     * Gets the attribute value for KONSULT using the alias name Konsult.
     * @return the KONSULT
     */
    public BigDecimal getKonsult() {
        return (BigDecimal) getAttributeInternal(KONSULT);
    }

    /**
     * Sets <code>value</code> as attribute value for KONSULT using the alias name Konsult.
     * @param value value to set the KONSULT
     */
    public void setKonsult(BigDecimal value) {
        setAttributeInternal(KONSULT, value);
    }


    /**
     * Gets the attribute value for MONTAG using the alias name Montag.
     * @return the MONTAG
     */
    public BigDecimal getMontag() {
        return (BigDecimal) getAttributeInternal(MONTAG);
    }

    /**
     * Sets <code>value</code> as attribute value for MONTAG using the alias name Montag.
     * @param value value to set the MONTAG
     */
    public void setMontag(BigDecimal value) {
        setAttributeInternal(MONTAG, value);
    }

    /**
     * Gets the attribute value for DOSTAVKA using the alias name Dostavka.
     * @return the DOSTAVKA
     */
    public BigDecimal getDostavka() {
        return (BigDecimal) getAttributeInternal(DOSTAVKA);
    }

    /**
     * Sets <code>value</code> as attribute value for DOSTAVKA using the alias name Dostavka.
     * @param value value to set the DOSTAVKA
     */
    public void setDostavka(BigDecimal value) {
        setAttributeInternal(DOSTAVKA, value);
    }

    /**
     * Gets the attribute value for BANK using the alias name Bank.
     * @return the BANK
     */
    public BigDecimal getBank() {
        return (BigDecimal) getAttributeInternal(BANK);
    }

    /**
     * Sets <code>value</code> as attribute value for BANK using the alias name Bank.
     * @param value value to set the BANK
     */
    public void setBank(BigDecimal value) {
        setAttributeInternal(BANK, value);
    }

    /**
     * Gets the attribute value for the calculated attribute KreditBoolean.
     * @return the KreditBoolean
     */
    public Boolean getKreditBoolean() {
        //return (Boolean) getAttributeInternal(KREDITBOOLEAN);
        if (this.getKredit()==1)
            return true;
        else
            return false;
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute KreditBoolean.
     * @param value value to set the  KreditBoolean
     */
    public void setKreditBoolean(Boolean value) {
        //setAttributeInternal(KREDITBOOLEAN, value);
        if (value)
            setKredit(1);
        else
            setKredit(0);
    }

    /**
     * Gets the attribute value for KONSULR_ID using the alias name KonsulrId.
     * @return the KONSULR_ID
     */
    public BigDecimal getKonsulrId() {
        return (BigDecimal) getAttributeInternal(KONSULRID);
    }

    /**
     * Sets <code>value</code> as attribute value for KONSULR_ID using the alias name KonsulrId.
     * @param value value to set the KONSULR_ID
     */
    public void setKonsulrId(BigDecimal value) {
        setAttributeInternal(KONSULRID, value);
    }

    /**
     * Gets the attribute value for MONTAG_ID using the alias name MontagId.
     * @return the MONTAG_ID
     */
    public BigDecimal getMontagId() {
        return (BigDecimal) getAttributeInternal(MONTAGID);
    }

    /**
     * Sets <code>value</code> as attribute value for MONTAG_ID using the alias name MontagId.
     * @param value value to set the MONTAG_ID
     */
    public void setMontagId(BigDecimal value) {
        setAttributeInternal(MONTAGID, value);
    }

    /**
     * Gets the attribute value for ZAMER_ID using the alias name ZamerId.
     * @return the ZAMER_ID
     */
    public BigDecimal getZamerId() {
        return (BigDecimal) getAttributeInternal(ZAMERID);
    }

    /**
     * Sets <code>value</code> as attribute value for ZAMER_ID using the alias name ZamerId.
     * @param value value to set the ZAMER_ID
     */
    public void setZamerId(BigDecimal value) {
        setAttributeInternal(ZAMERID, value);
    }

    /**
     * Gets the attribute value for RETURNED using the alias name Returned.
     * @return the RETURNED
     */
    public Integer getReturned() {
        return (Integer) getAttributeInternal(RETURNED);
    }

    /**
     * Sets <code>value</code> as attribute value for RETURNED using the alias name Returned.
     * @param value value to set the RETURNED
     */
    public void setReturned(Integer value) {
        setAttributeInternal(RETURNED, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Total_Cost.
     * @return the Total_Cost
     */
    public Number getTotal_Cost() {
        return (Number) getAttributeInternal(TOTAL_COST);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Total_Cost.
     * @param value value to set the  Total_Cost
     */
    public void setTotal_Cost(Number value) {
        setAttributeInternal(TOTAL_COST, value);
    }

    /**
     * Gets the attribute value for KONSULT_NAME using the alias name KonsultName.
     * @return the KONSULT_NAME
     */
    public String getKonsultName() {
        return (String) getAttributeInternal(KONSULTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for KONSULT_NAME using the alias name KonsultName.
     * @param value value to set the KONSULT_NAME
     */
    public void setKonsultName(String value) {
        setAttributeInternal(KONSULTNAME, value);
    }


    /**
     * Gets the attribute value for the calculated attribute Total_Summa.
     * @return the Total_Summa
     */
    public Number getTotal_Summa() {
        return (Number) getAttributeInternal(TOTAL_SUMMA);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Total_Summa.
     * @param value value to set the  Total_Summa
     */
    public void setTotal_Summa(Number value) {
        setAttributeInternal(TOTAL_SUMMA, value);
    }


    /**
     * Gets the attribute value for MONTAG_NAME using the alias name MontagName.
     * @return the MONTAG_NAME
     */
    public String getMontagName() {
        return (String) getAttributeInternal(MONTAGNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for MONTAG_NAME using the alias name MontagName.
     * @param value value to set the MONTAG_NAME
     */
    public void setMontagName(String value) {
        setAttributeInternal(MONTAGNAME, value);
    }

    /**
     * Gets the attribute value for ZAMER_NAME using the alias name ZamerName.
     * @return the ZAMER_NAME
     */
    public String getZamerName() {
        return (String) getAttributeInternal(ZAMERNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for ZAMER_NAME using the alias name ZamerName.
     * @param value value to set the ZAMER_NAME
     */
    public void setZamerName(String value) {
        setAttributeInternal(ZAMERNAME, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link OrdersTabPartOplatyView.
     */
    public RowIterator getOrdersTabPartOplatyView() {
        return (RowIterator)getAttributeInternal(ORDERSTABPARTOPLATYVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link AccCostView.
     */
    public RowIterator getAccCostView() {
        return (RowIterator)getAttributeInternal(ACCCOSTVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> KonsultNameView1.
     */
    public RowSet getKonsultNameView1() {
        return (RowSet)getAttributeInternal(KONSULTNAMEVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> VwOrderView1.
     */
    public RowSet getVwOrderView1() {
        return (RowSet)getAttributeInternal(VWORDERVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> MontagNameView1.
     */
    public RowSet getMontagNameView1() {
        return (RowSet)getAttributeInternal(MONTAGNAMEVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ZamerNameView1.
     */
    public RowSet getZamerNameView1() {
        return (RowSet)getAttributeInternal(ZAMERNAMEVIEW1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
