package falcon.view;

import falcon.view.common.ZamerNameLookupVO;

import model.FalconFiltersViewObjectImpl;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 20 18:46:16 EET 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ZamerNameLookupVOImpl extends FalconFiltersViewObjectImpl implements ZamerNameLookupVO {
    /**
     * This is the default constructor (do not remove).
     */
    public ZamerNameLookupVOImpl() {
    }

    /**
     * Returns the bind variable value for u_name.
     * @return bind variable value for u_name
     */
    public String getu_name() {
       // return (String)getNamedWhereClauseParam("u_name");
       return  getSessionUserName();
    }

    /**
     * Sets <code>value</code> for bind variable u_name.
     * @param value value to bind as u_name
     */
    public void setu_name(String value) {
        setNamedWhereClauseParam("u_name", value);
    }

    /**
     * Returns the variable value for SearchCriteria.
     * @return variable value for SearchCriteria
     */
    public String getSearchCriteria() {
        return (String)ensureVariableManager().getVariableValue("SearchCriteria");
    }

    /**
     * Sets <code>value</code> for variable SearchCriteria.
     * @param value value to bind as SearchCriteria
     */
    public void setSearchCriteria(String value) {
        ensureVariableManager().setVariableValue("SearchCriteria", value);
    }
}
