package falcon.view;

import falcon.view.common.ZatratyPostView;

import java.math.BigDecimal;

import model.ArticleIsNull;
import model.FalconFiltersViewObjectImpl;

import oracle.jbo.server.ViewObjectImpl;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Dec 10 20:51:10 EET 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ZatratyPostViewImpl extends FalconFiltersViewObjectImpl implements ZatratyPostView {
    /**
     * This is the default constructor (do not remove).
     */
    public ZatratyPostViewImpl() {
    }

    public void createZatratyArticle(BigDecimal id_par, String za) {
        try {
            if (za.isEmpty())
                throw new ArticleIsNull(za);
            else {
                BigDecimal u_id = getSessionUserId();
                callStoredProcedure("zatraty_pkg.insert_zatraty(?,?,?)", new Object[] { u_id, id_par, za });
            }
        } catch (ArticleIsNull e) {
            System.out.println(e.toString());
        }

    }
}
