package falcon.view.client;

import falcon.view.common.CatalogMetaTablesView;

import oracle.jbo.Row;
import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 11 19:42:43 EET 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CatalogMetaTablesViewClient extends ViewUsageImpl implements CatalogMetaTablesView {
    /**
     * This is the default constructor (do not remove).
     */
    public CatalogMetaTablesViewClient() {
    }

    public String getRowStatus(Row row) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getRowStatus",new String [] {"oracle.jbo.Row"},new Object[] {row});
        return (String)_ret;
    }
}
