package falcon.view.client;

import falcon.view.common.ObmenSettingsView;

import java.math.BigDecimal;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Dec 09 17:59:25 EET 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ObmenSettingsViewClient extends ViewUsageImpl implements ObmenSettingsView {
    /**
     * This is the default constructor (do not remove).
     */
    public ObmenSettingsViewClient() {
    }

    public void doSynchronization(BigDecimal id) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"doSynchronization",new String [] {"java.math.BigDecimal"},new Object[] {id});
        return;
    }
}
