package falcon.view.client;

import falcon.view.common.VwBepView;

import oracle.jbo.client.remote.ViewUsageImpl;
import oracle.jbo.domain.Date;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jan 29 16:45:03 EET 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VwBepViewClient extends ViewUsageImpl implements VwBepView {
    /**
     * This is the default constructor (do not remove).
     */
    public VwBepViewClient() {
    }

    public Date getu_dat() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"getu_dat",null,null);
        return (Date)_ret;
    }
}
