package falcon.view.client;

import falcon.view.common.VwSalesReportView;

import oracle.jbo.client.remote.ViewUsageImpl;
import oracle.jbo.domain.Date;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jan 25 19:48:09 EET 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VwSalesReportViewClient extends ViewUsageImpl implements VwSalesReportView {
    /**
     * This is the default constructor (do not remove).
     */
    public VwSalesReportViewClient() {
    }

    public void setu_dat(Date value) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"setu_dat",new String [] {"oracle.jbo.domain.Date"},new Object[] {value});
        return;
    }
}
