package falcon.view.client;

import falcon.view.common.VwSalesPerMonthView;

import oracle.jbo.client.remote.ViewUsageImpl;
import oracle.jbo.domain.Date;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jan 25 19:55:43 EET 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VwSalesPerMonthViewClient extends ViewUsageImpl implements VwSalesPerMonthView {
    /**
     * This is the default constructor (do not remove).
     */
    public VwSalesPerMonthViewClient() {
    }

    public void setu_dat(Date value) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"setu_dat",new String [] {"oracle.jbo.domain.Date"},new Object[] {value});
        return;
    }

    public void setu_name(String value) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"setu_name",new String [] {"java.lang.String"},new Object[] {value});
        return;
    }
}
