package falcon.view.client;

import falcon.view.common.ZamerNameLookupVO;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 20 18:52:33 EET 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ZamerNameLookupVOClient extends ViewUsageImpl implements ZamerNameLookupVO {
    /**
     * This is the default constructor (do not remove).
     */
    public ZamerNameLookupVOClient() {
    }

    public void setSearchCriteria(String value) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"setSearchCriteria",new String [] {"java.lang.String"},new Object[] {value});
        return;
    }
}
