package falcon.view.client;

import falcon.view.common.ZatratyPostView;

import java.math.BigDecimal;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Dec 10 20:54:27 EET 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ZatratyPostViewClient extends ViewUsageImpl implements ZatratyPostView {
    /**
     * This is the default constructor (do not remove).
     */
    public ZatratyPostViewClient() {
    }

    public void createZatratyArticle(BigDecimal id_par, String za) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"createZatratyArticle",new String [] {"java.math.BigDecimal","java.lang.String"},new Object[] {id_par, za});
        return;
    }
}
